### ISSUE TITLE
Only parameterless function imports should be included in the service document

### ISSUE THREAD

**Issue by congysu** [OData/odata.net#104]
Refer to the https://github.com/OData/WebApi/issues/244

**Comment by TomDu** [comment]
Fixed.

**Comment by SimonPStevens** [comment]
Can anyone explain why only parameterless functions are included in the service doc? I know it's what the OData spec says, but is there a reason for it being like that?

I'm trying to integrate Power BI with an OData API, and the fact that functions with parameters are not included in the service doc makes the integration much less useful.

**Comment by shaunpenfold** [comment]
Facing the same issue as @SimonPStevens  question?Also developed an OData API and now all functions with parameters are not available in powerbi or excel. Yet if i point power query to the sample odata API((https://services.odata.org/v4/TripPinService/)) i find a function with parameters (GetNearestAirport)?

**Comment by SimonPStevens** [comment]
@shaunpenfold FYI, the latest Power BI reverts this behaviour. They have now gone back to inferring the functions url and displaying them in the navigator.

This doesn't mean the problem is fixed, I do think there needs to be a standard way that these functions are described in the OData service document. But at least for now Power BI and Excel work around the issue.
