### ISSUE TITLE
Feature Request: develop pluggable parser for JSON reader

### ISSUE THREAD

**Issue by AlanWong-MS** [OData/odata.net#1183]
A change in #1165 where parens parsing, which is not a JSON concept, is added to the JsonReader has raised consideration for a pluggable parser. This issue is to track this particular feature request.

**Comment by mikepizzo** [comment]
In particular, change #1165 uses the underlying (possibly dependency-injected) parser to parse the parens-style collection within the URL.  As this is not standard JSON, an arbitrary JSON parser plugged into the framework will probably fail to parse this correctly.  

Thinking about this a bit more; the use of the JSON parser to parse this is an implementation detail and shouldn't break because the parser the user plugged in for JSON serialization doesn't support this non-standard syntax.  I think we should figure out a way to make sure that the JSON reader used to parse the text is our own.
