### ISSUE TITLE
Client Code Gen ignores IgnoreUnexpectedAttributesAndElements flag for VB

### ISSUE THREAD

**Issue by AlanWong-MS** [OData/odata.net#1197]
### Assemblies affected
ODL 7.4.0

### Description
When setting the IgnoreUnexpectedAttributesAndElements option for Client Code Gen ttinclude, the generated code does not include the setting. #1150 addresses the C# side but additional effort is needed for the VB side. This issue is to track the VB side.

**Comment by gathogojr** [comment]
This issue is fixed in OData Connected Service extension the successor of CodeGen. Refer to [this test](https://github.com/OData/ODataConnectedService/blob/f60a6957d124c54739e2bbad3e62a3ec0f486776/test/ODataConnectedService.Tests/Templates/ODataT4CodeGeneratorTests.cs#L495) to confirm IgnoreUnexpectedAttributesAndElements flag is respected for both C# and VB
