### ISSUE TITLE
DateTimeOffset is not serialized to ISO Datetime string in response

### ISSUE THREAD

**Issue by brijeshb** [OData/odata.net#1289]
*DateTimeOffset is not serialized to ISO Datetime string in response*

### Reproduce steps

Have entity with DateTimeOffset prorperty.
Run on asp.net core 2.1 with latest odata nuget.

### Expected result

{ time: "2018-10-11T02:14:02.7346039Z" }

### Actual result

{ time: "2018-10-10T19:14:02.7346039-07:00" }

**Comment by biaol-odata** [comment]
ABNF spec for DateTimeOffset ([sec 14.3.4](http://docs.oasis-open.org/odata/odata-csdl-json/v4.01/cs01/odata-csdl-json-v4.01-cs01.html#BMABNF) ) specifies it should be conform to xs:dateTimeStamp, which says:
```
The result is that all values of dateTimeStamp are required to have explicit time zone offsets and the datatype is totally ordered.
```
However, it provides the following example:
```
"@UI.LastUpdated": {

  "$DateTimeOffset": "2000-01-01T16:00:00.000Z"

}
```

@mikepizzo can you please confirm whether ISO Datetime is the expected behavior?

**Comment by brijeshb** [comment]
Ping

**Comment by jpiquot** [comment]
Hi @brijeshb ,
For me the result is correct, it's your data that contains local time instead of UTC time. If you want UTC, you have to convert local time to UTC before saving in your database or when retrieving it.

**Comment by KenitoInc** [comment]
Question has been answered
