### ISSUE TITLE
Am I supposed to create a new instance of the DataServiceContext on each request?

### ISSUE THREAD

**Issue by kornakar** [OData/odata.net#1290]
I'm using the generated client code in a WCF service. I originally used the DataServiceContext as a singleton, but quickly noticed that the EntityTracker is keeping track of all the entities read from an OData API (DataServiceContext.TrackedEntities).

Is this by design so that I should create a new instance of the DataServiceContext on each request? I would like to use only one instance because creating a new one for every request has performance implications.

### Assemblies affected

7.5.0.20627

### Expected result

TrackedEntities should be cleared.

### Actual result

The TrackedEntities keeps increasing forever (?).

**Comment by habbes** [comment]
@kornakar the tracked entities collection doesn't necessarily keep growing, if you fetch the same entities on different requests, the corresponding entities in the tracker (as determined by ID) will be updated instead of creating new ones. If you fetch different entities on different requests, then it might continue to grow, the size should be proportional to the total number of unique entities that are fetched by the client. If this size is too big for your application, maybe you could disable client-side tracking.
