### ISSUE TITLE
Microsoft.OData.Client not working in Xamarin projects

### ISSUE THREAD

**Issue by JanKonopka** [OData/odata.net#1382]
Microsoft.OData.Client doesn't work with newest version of Visual Studio and Xamarin projects.

### Assemblies affected

All that I tested.

### Reproduce steps

1. Create new Xamarin.Forms app in Visual Studio.
2. Add new Connected Service using odata client.
3. Any request made simply hangs.

In VS 15.7.6 requests pass in Android (although bad requests are not caught), still doesn't work on iOS.

**Comment by KanishManuja-MS** [comment]
@JanKonopka Can you help us reproduce this at our end? Any sample projects would be appreciated. 
Do you know if this works with the previous version of visual studio as your descriptions hints towards visual studio is the culprit here?

**Comment by marabooy** [comment]
@JanKonopka The issue was fixed in https://docs.microsoft.com/en-us/visualstudio/releasenotes/vs2017-relnotes#15.9.7 and https://github.com/mono/mono/issues/10488
Upgrading to either VS2019 or VS2017 15.9.7 should sort it out. Kindly do let me know if you face any issue related to this so we can reopen the issue.

Also do make sure to run the queries using the exposed async api's e.g 
`   var airlines = await container.Airlines.ExecuteAsync() ` to get airlines from a service
