### ISSUE TITLE
OData.Client: Support for DataAnnotations key attribute

### ISSUE THREAD

**Issue by boppbo** [OData/odata.net#150]
I share my dtos between server and client applications. The server components support the usual DataAnnotations attributes.

Unfortunately the client doesn't. As I don't want to install any odata package into my model, I created a custom OData client package that recognizes more key attributes .(boppbo/odata.net@68518c8d7e3743591f7afa8ce93407b5f8332e30)

Are there any plans to implement something similar upstream?

**Comment by boppbo** [comment]
Hi,

are there any news on this issue? Are .NET DataAnnotations supported meanwhile?
Is there any kind of contribution desirable?

With kind regards

**Comment by mikepizzo** [comment]
Hi boppbo;  we'd love to see a contribution for this if it is still an important scenario to you and others.  Closing according to our [triage guidelines](https://github.com/OData/WebApi/blob/master/.github/ISSUE_TRIAGE.md) so that you get notified, but would be happy to review a contribution for this.
