### ISSUE TITLE
the code generator wrong code if the metadata has entiryset name container

### ISSUE THREAD

**Issue by gordonsnc** [OData/odata.net#1545]
the code generator wrong code if the metadata has entityset name containers,
the generated code can not compile
### Assemblies affected

Latest version 7.5.1

Has a Odata service, that    
uri/Odata/$metadata returns has this
<EntityContainer Name="MyProd">
    <EntitySet Name="Containers" ..>
    .......

### Expected result

the code should works like normal

### Actual result

Lots of this compile error message come up:
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'ContainerSingle' does not contain a definition for 'CreateQuery' and no accessible extension method 'CreateQuery' accepting a first argument of type 'ContainerSingle' could be found (are you missing a using directive or an assembly reference?)

**Comment by paulodero** [comment]
@gordonsnc Is it possible to share the full Edmx you are using to generate code?

**Comment by paulodero** [comment]
@gordonsnc This issue is being closed. If you are still experiencing the issue please feel free to reopen and provide the requested Edmx and more information to help reproduce the issue you are facing. I have tried to code generator 7.5.1 with an Edmx that has <EntitySet Name="Containers" ..> and it generates correct code that compiles.
