### ISSUE TITLE
OrderBy specify null first or null last?

### ISSUE THREAD

**Issue by EnthusedDragon** [OData/odata.net#1592]
Does OData allow us to specify for null values to come before non-null values in ascending order and consequently after non-null values in descending order?
I can't find any documentation regarding such a feature.

### Assemblies affected
Microsoft.AspNetCore.OData (7.2.2)

### Reproduce steps
Ordering by ASC forces all null values to the end of the list.
Ordering by DESC forces all null values to the top of the list.

### Expected result
Set a flag to true for null first or false for null last

### Actual result
Ordering by ASC forces all null values to the end of the list.
Ordering by DESC forces all null values to the top of the list.

**Comment by xuzhg** [comment]
@EnthusedDragon  From [OData spec](https://docs.oasis-open.org/odata/odata/v4.01/csprd06/part1-protocol/odata-v4.01-csprd06-part1-protocol.html#_Toc21423809) says:

`Null values come before non-null values when sorting in ascending order and after non-null values when sorting in descending order.`

ODL only parse the $orderby and output the Orderby clause, Web API OData consumes the clause and generate the Linq expression. The data source provider should take case of that case.

**Comment by EnthusedDragon** [comment]
@xuzhg 
I saw that in the OData spec, unfortunately it's doing the opposite for my.

The OData query is being executed on an IQueryable coming from Entity Framework, connected to a PostgreSQL Database.

**Comment by gathogojr** [comment]
@EnthusedDragon Just like @xuzhg said, the data source provider determines the sort order. You mentioned that you're using PostgreSQL. According to the the [documentation](https://www.postgresql.org/docs/current/queries-order.html#:~:text=By%20default%2C%20null%20values%20sort,independently%20for%20each%20sort%20column.), by default, null values sort as if larger than any non-null value; that is, NULLS FIRST is the default for DESC order, and NULLS LAST otherwise. You can tweak that at the database level to control the behaviour. I'll go ahead and close this issue for now. Feel free to reopen if you feel it hasn't been adequately addressed
