### ISSUE TITLE
Can odata.net be configured to output snake_case JSON?

### ISSUE THREAD

**Issue by atrauzzi** [OData/odata.net#1638]
I would love to be able to configure the output of my odata endpoints to be `snake_case` rather than `camelCase` or `PascalCase`! 🙂

**Comment by Sreejithpin** [comment]
@atrauzzi , You can create snake_case properties and that's totally valid. Or did you want an auto conversion from camelCase or PascalCase properties (in edm model )to snake_case for json o/p?

**Comment by atrauzzi** [comment]
Auto conversion in EDM.  I'm working with a model that's reverse engineered out of an existing DB that follows that convention. I don't want my .net types to be impacted by something like that. 😉

**Comment by odero** [comment]
@atrauzzi There's no auto-conversion support however you should be able to user the `DataMember` attribute to generate in snake_case https://docs.microsoft.com/en-us/dotnet/api/system.runtime.serialization.datamemberattribute
Would that work for your case?

**Comment by atrauzzi** [comment]
Sadly no as that would require me to create definitions for hundreds of properties in an auto generated model. Would also be fault prone as new models are added.

I need an automatic, conventions based approach.

**Comment by ChrisSchaller** [comment]
I would use a T4 script to define the properties in the model, that gives you automation and customisation at the same time.

**Comment by atrauzzi** [comment]
Yikes, that sounds like overkill, also, I don't want to mix any concerns in the models.

This needs to be configurable at the serialization layer as the functionality is already there.

**Comment by ChrisSchaller** [comment]
But it's not just serialization, you would also have to override the URI resolver or Routing Convention as well but even then the $metadata will still need to be overridden if you wanted to support any OData client-side generation or inspection tools. Instead of T4 you could just iterate all the types in the ODataBuilder and set the name on all the properties to a snake_case variant.

Conventions are not really an option here as `ODataConventionModelBuilder` is not extensible, the convention must implement some internal interfaces and they are hardcoded into a static internal array. You can't even get around this easily by inheriting from `ODataConventionModelBuilder`, again because the types and properties you need access to are marked as _internal_.

You could submit a PR to allow custom convention implementation similar to EF... otherwise T4 is not so much an overkill solution any more.

**Comment by ChrisSchaller** [comment]
@atrauzzi you mention your model is _reverse engineered_ did you use a repeatable tool to do this, or was it once off? You could instead augment the reverse logic to add the `DataMemberAttribute` at the time the class is created.

**Comment by atrauzzi** [comment]
Again, I think the `DataMemberAttribute` is an implementation specific that's inappropriate for the model.

That said, I'm using the EF reverse migration tool. I don't want to have my hands in it.  The right place for this is somewhere in the odata layer where I tell it to follow a consistent policy for mapping properties to json field names.

**Comment by KenitoInc** [comment]
Closing this.
Feel free to create a new issue if there are any more questions to be answered.

**Comment by atrauzzi** [comment]
Yeah, np.  Odata is a pretty dead tech anyway.

**Comment by ChrisSchaller** [comment]
I disagree with that comment and would consider anything that uses/needs snake case as pretty archaic. It's trival to make OData case insensitive but to inject additional underscores bloats the JSON payload considerably.

 It is however trival to tweak whatever script/tool you used to generate the model from your existing database such that either the model itself uses snake_case or the OData model uses snake case only for the properties, you just can't do it via a serializer. Probably should have made this clearer the first time, I was focusing on the wrong problem.

Because routing needs to be affected you must do this in the ODataConventionModelBuilder implementation, so when you configure each field you would explicitly map the snake_case output if you really needed it. A simple T4 script would be advisable here to pickup any future changes to your model, but you can generate once and save the output if you are not a fan of code generators or templates.

________________________________
