### ISSUE TITLE
The Id cannot be computed, since the navigation source 'values' cannot be resolved to a known entity set from model

### ISSUE THREAD

**Issue by Echarnus** [OData/odata.net#1666]
I created a OData service I am consuming via Simple.OData.Client, yet am receiving the error at following code: 

```
private ODataEntryAnnotations CreateAnnotations(ODataResource odataEntry)
        {
            string id = null;
            Uri readLink = null;
            Uri editLink = null;
            if (_session.Adapter.GetMetadata().IsTypeWithId(odataEntry.TypeName))
            {
                try
                {
// Over here my exception occurs, calculating the odataEntry.Id.AbsoluteUri
                    id = odataEntry.Id.AbsoluteUri;
                    readLink = odataEntry.ReadLink;
                    editLink = odataEntry.EditLink;
                }
                catch (ODataException)
                {
/// Yep, the library contains this typo
                    // Ingored
                }
            }

            return new ODataEntryAnnotations
            {
                Id = id,
                TypeName = odataEntry.TypeName,
                ReadLink = readLink,
                EditLink = editLink,
                ETag = odataEntry.ETag,
                MediaResource = CreateAnnotations(odataEntry.MediaResource),
                InstanceAnnotations = odataEntry.InstanceAnnotations,
            };
        }
```

### Assemblies affected

Microsoft.OData.Core version 7.6.3

### Reproduce steps

Each time I receive an OData item

### Expected result

No exception

### Actual result

Following exceptions with each OData record get thrown, causing too much overhead on our system: 

Microsoft.OData.ODataException: 'The Id cannot be computed, since the navigation source 'values' cannot be resolved to a known entity set from model.'

### Additional detail

Made an 'in depth' post about it at StackOverflow

https://stackoverflow.com/questions/60188656/the-id-cannot-be-computed-since-the-navigation-source-values-cannot-be-resolv

Is my OData service wrong or is there a workaround for this behaviour?

**Comment by xuzhg** [comment]
From the Stackoverflow, "Contained" attribute resolves your problem.  I'd like share more information about the error message. 

From OData repo, we have the following error message definition:
`ODataMetadataBuilder_UnknownEntitySet=The Id cannot be computed, since the navigation source '{0}' cannot be resolved to a known entity set from model.`

So, For "Non-containment navigation property", you should have the "Navigation property binding" for them, otherwise, OData core can't compute the "Id" and throw "UnknowEntitySet" error message.

For "containment navigation property", don't set the "navigation property binding" for them. OData core don't need to compute the "Id" for "containment navigation property.
