### ISSUE TITLE
EDM Model with Keyless Entity 

### ISSUE THREAD

**Issue by maulik-modi** [OData/odata.net#1724]
As EF Core now has first class support for keyless entity, it is worth supporting in OData for fullest advantage. 

### Assemblies affected
OData.net

### Reproduce steps
Create database view
Create EF Core entity with HasNoKey
Create EDM Model

### Expected result
Able to Get EDM Model with Keyless entity

var edmBuilder = new ODataConventionModelBuilder();
edmBuilder.EntitySet<Student>("Students");       
return edmBuilder.GetEdmModel();

### Actual result

*What is actually happening.*
I get an error on this line edmBuilder.GetEdmModel() The entity set 'Students' is based on type 'ODataCore31.Student' that has no keys defined.

### Additional detail
Added stackvoerflow question https://stackoverflow.com/questions/60847616/how-can-i-expose-querable-api-using-odata-for-ef-core-keyless-entitydatabase-vi

**Comment by KenitoInc** [comment]
@maulik-modi 
Entities used within a collection must have a key so that we can uniquely identify them.
It's possible to have a collection of complex types (which do not have keys) as a member of an entity. You can define singleton at the root that contains a collection of complex types. But you will be limited in what you can do with that collection . For instance you cannot update/delete an individual member. 
Keys are strongly preferred for resources within a collection.
Please let us know if there are reason that this doesn't work for your scenario.

**Comment by maulik-modi** [comment]
We want to use OData to facilitate ReadModel \ Query part of CQRS Architecture where we create database views joining multiple tables and hence there is no Unique key, it is Keyless entity. We do not intend to perform add\edit operation using this.
