### ISSUE TITLE
Support Metadata as a service

### ISSUE THREAD

**Issue by congysu** [OData/odata.net#181]
Allow read schema elements: types, operations, and also entity container elements: entity sets, operation imports.
[15      Metadata Service Schema](http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part3-csdl/odata-v4.0-errata02-os-part3-csdl-complete.html#_Toc406398100)
[MetadataService.edmx](http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/models/MetadataService.edmx)

Related issues: https://github.com/OData/odata.net/issues/54 https://github.com/OData/odata.net/issues/88

**Comment by abkmr** [comment]
Also needed for Dynamics CRM

**Comment by xuzhg** [comment]
Related: http://stackoverflow.com/questions/35543769/fetching-metadata-for-a-specific-collection-or-entity-with-odata-web-services-i

**Comment by jslegers** [comment]
@xuzhg  :

Thanks for referencing this issue on my StackOverflow question.

So I guess this means that Odata's metadata are really nothing but a single static XML file today?!

I guess that explains why there's no Json support either.

**Comment by habbes** [comment]
Would fetching the metadata, parsing and extracting information from it be a viable solution? For example, parsing a csdl using `CsdlReader` returns an `IEdmModel` which allows get all sorts of information from the model. We do support a CSDL JSON format as well, which would make it easier to parse the model on web clients using JS.

If these alternatives are not viable, I would suggest creating a new issue for a feature request since the `$metadata` endpoint currently behaves as designed based on the spec.
