### ISSUE TITLE
ResolveOperationFromList not allowing unqualified function names on open types

### ISSUE THREAD

**Issue by Casimodo72** [OData/odata.net#200]
Hi,
FunctionOverloadResolver.ResolveOperationFromList does not allow unqualified function names on open types (yet?) making OData Web API's EnableUnqualifiedNameCall(true) option ineffective.

See https://github.com/OData/WebApi/issues/360

Regards,
Kasimier Buchcik

**Comment by karataliu** [comment]
I checked the webapi issue, and looks you've reached the right place:

https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/UriParser/Parsers/FunctionOverloadResolver.cs#L123-L135 

For now, it doesn't support unqualified name to be used as function for open types, just because previous validation. And we could allow this when users are using an extended UriResolver, will put this issue into backlog.

Refer to following code, to do loose validation for non-default UriResolver.
https://github.com/OData/odata.net/blob/ae0dd29c1cf430255a8ec9c4225b4745e25cad64/src/Microsoft.OData.Core/UriParser/Parsers/ODataPathParser.cs#L230

**Comment by congysu** [comment]
Cost estimation: Small <=~1 week effort.

**Comment by TomDu** [comment]
Merged, thanks.
