### ISSUE TITLE
Sporadic errors in ODataContextUrlInfo 

### ISSUE THREAD

**Issue by korygin** [OData/odata.net#2057]
When navigating to a contained navigation property under the stress load, about 5% of requests are failing with the following error:

_Microsoft.OData.ODataException: 'The Path property '{Entity Set Name}' of ODataMessageWriterSetting.ODataUri must end with the navigation property which the contained elements being written belong to.'_

### Assemblies affected

Microsoft.OData.Core v 7.8.3

### Reproduce steps

The issue is sporadic and only appears in ~ 5% of requests which may indicate a potential concurrency issue. The error is thrown from _ODataContextUrlInfo_ class, _ComputeNavigationPath()_ method, line # 260.

### Expected result

A proper OData response is returned.

### Actual result

An HTTP 200 (OK) response with broken partial JSON payload is returned.

### Additional detail

The issue appears to be with incorrect OData path in the _ODataMessageWriterSettings_. The following can be observed in _ODataResourceSetSerializer.WriteObjectAsync()_ method:
- _writeContext.InternalRequest.RequestUri.ToString()_ returns  "{base URI}/Services(78a6f9e9-1c6a-475a-ba23-f41daa34124a)/Groups" where Groups is a contained navigation property of Service entity type.
- _writeContext.Path_ correctly shows 3 segments:
   {Services(78a6f9e9-1c6a-475a-ba23-f41daa34124a)/Groups}
    EdmType: {Collection([Com.Ingr.ApiManagement.V1.ServiceGroup Nullable=False])}
    NavigationSource: Name:"Groups"
    Path: {Microsoft.OData.UriParser.ODataPath}
    PathTemplate: "~/entityset/key/navigation"
    Segments: Count = 3
- However, _messageWriter.Settings.ODataUri.Path_ contains only one entity set segment thus error in _ODataContextUrlInfo_ line # 260:
    Count: 1
    FirstSegment: {Microsoft.OData.UriParser.EntitySetSegment}
    LastSegment: {Microsoft.OData.UriParser.EntitySetSegment}
    Segments: Count = 1

**Comment by habbes** [comment]
Hi @korygin thanks for raising this. Could you kindly share the code and information about the environment and setup you used to uncover this issue so that we can try to reproduce it and investigate it further?

**Comment by korygin** [comment]
I'm attaching a simple OData service project to demo the problem. You can use EF migrations to initialize the database by running the following commands in the Package Manager Console:

- Add-Migration Initial
- Update-Database

In the project folder there is StoredODataService.saz file that contains Fiddler sessions. If you start the service in debugger and then replay sessions in Fiddler you should see the error (may take a few runs but eventually it'll break). Hope this helps.

[StoreODataService.zip](https://github.com/OData/odata.net/files/6399905/StoreODataService.zip)

**Comment by dlbrann** [comment]
@habbes , what is the status of this issue?   Were you able to reproduce it using @korygin's test case?

**Comment by habbes** [comment]
Hi @korygin @dlbrann. Apologies for the delay in getting back. I finally got an opportunity to take a deeper look into this:

I was not able to reproduce the issue with the project you shared, but I noticed that the project did not have any date. The migrations only initialized the table.

However, I think I've found a potential culprit for the issue. I noticed the following block of code in your `Extension.cs` file where you're configuring the route's container:

```c#
// Disable type metadata checks to allow Edm.Stream properties
// and improve performance.
containerBuilder.AddService(Microsoft.OData.ServiceLifetime.Singleton,
     typeof(ODataMessageWriterSettings),
     sp => new ODataMessageWriterSettings()
         {
             Validations = ValidationKinds.All & ~ValidationKinds.ThrowIfTypeConflictsWithMetadata
         });
```

You're registering the `ODataMessageWriterSettings` as a singleton, meaning the same instance is shared across all requests. The default `ODataMessageWriterSettings` is meant to have a `Scoped` lifetime (that's how it's registered by default).

Before the formatter writes the output, it retrieves the `ODataMessageWriterSettings` from the service container and then creates a new `ODataUri` objects and sets it as the `writerSettings.ODataUri` property. This is problematic if you have multiple requests sharing the same `writerSettings` object. It is possible that while one request is in the middle of being processed, another request will start getting written and cause the `ODataUri` property to be change. This will cause a mismatch between the ODataUri and the expected path of the first request, leading to exceptions like the ones you observed.

I haven't yet verified that this will solve the problem since I was not able to reproduce the issue. Please try registering the writer settings as `ServiceLifetime.Scoped` and see if it solves the issue. If you can provide a repro with the same dataset you tested with, I'd be happy to test it out more as well.

**Comment by habbes** [comment]
@korygin thanks.

**Comment by habbes** [comment]
@korygin glad to hear that. Thanks for getting back.
