### ISSUE TITLE
OData Lib supports .NET Native

### ISSUE THREAD

**Issue by congysu** [OData/odata.net#215]
Compile with .NET Native tool chain
Related info:
https://msdn.microsoft.com/en-us/library/dn600164(v=vs.110).aspx
http://stackoverflow.com/questions/22852958/how-do-i-enable-net-native-on-my-application

**Comment by lewischeng-ms** [comment]
Workitem 1: #237

Status: In progress

**Comment by lewischeng-ms** [comment]
Workitem 2: #238 

Status: In progress

**Comment by lewischeng-ms** [comment]
Sample universal app: https://github.com/OData/ODataSamples/commit/d007ed600b599e211304ba01eb22a1b7b5859255

**Comment by MattWhilden** [comment]
Hello! I work on the .NET Native runtime and compiler team. Is this issue still open? If you end up seeing weird things (or just want a few pointers) feel free to send us a mail at dotnetnative@microsoft.com.

**Comment by lewischeng-ms** [comment]
@MattWhilden Thanks for your help! This issue is still open but we are actually waiting for enough customer ask and team resource to continue on the work. I've already done some early investigation and had a list of code changes necessarily to happen in our codebase. Previously we did have some unresolved issues but given .NET Native must have been evolved much during this period, we can't exactly tell how many of those weird issues left for the time being. We will ask for your help when we really get to them. Thanks again!

**Comment by MattWhilden** [comment]
Sounds great. There's another round of amazing improvements coming with Update 2 sometime around //BUILD. Happy to hear your thoughts at any time. Keep me posted. :-)

**Comment by lewischeng-ms** [comment]
@MattWhilden Sure and thanks for the great news!
