### ISSUE TITLE
Performance - Excessive Enumerator objects created in hot paths

### ISSUE THREAD

**Issue by habbes** [OData/odata.net#2190]
A lot of `Enumerator` instances are getting allocated. This is due to using `foreach`  and LINQ against `IEnumerable`s on hot paths.

In cases where the collection provides a cheap way to get the count and has cheap random access (e.g. `List<T>` and arrays) we could consider using simple `for` loops and accessing elements by index directly. It would probably make the code less readable/elegant, but the savings would add up to > 1% allocation savings in AGS.

Here are some of the "hot" loops we could consider optimizing:
- `JsonLightInstanceAnnotationWriter.WriteInstanceAnnotations(IEnumerable<ODataInstanceAnnotation>, InstanceAnnotationWriteTracker, bool, string)` has a `foreach` loop that's used on `List<T>` instances
- `ODataJsonLightResourceSerializer.WriteResourceEndMetadataProperties(IODataJsonLightWriterResourceState, IDuplicatePropertyNameChecker)`: this function calls `actions.Any()` and `functions.Any()`, calling `Any()` causes the `List<T>.GetEnumerator()` to be called. I don't completely understand this because from the `Enumerable.Any` [source code](https://source.dot.net/#System.Linq/System/Linq/AnyAll.cs,11), it's not supposed to call `GetEnumerator` if the `IEnumerable<T>` also implements `ICollection<T>`, which `List<T>` does, in such cases it's supposed to check `Count != 0`.
- `Edm.ExtensionMethods.FindVocabularyAnnotations(IEdmModel, IEdmVocabularyAnnotatable)` has a `foreach` loop.
- `ODataWriterCore.AppendEntitySetKeySegment(ODataPath, bool)` has a `foreach (IEdmStructuralProperty property in currentEntityType.Key())` loop
- `ODataPath.ctor(IEnumerable<ODataPathSegments)` (the constructor) passes the segments `IEnumerable` to the `List` constructor, the `List` constructor iterates over the collection to add the elements to the list. Not sure if this can be optimized easily.
- `.ODataJsonLightValueSerializer.WriteCollectionValue(ODataCollectionValue, IEdmTypeReference, IEdmTypeReference, bool, bool, bool)` has a `foreach (object item in items)` loop
- Use of `scopeStack.First()` in `ODataWriterCore` (not sure if this can be easily optimized)
- `ODataResourceBase.VerifyProperties(IEnumerable<ODataProperty>)`
- `ODataJsonLightPropertySerializer.WriteProperties`

![image](https://user-images.githubusercontent.com/8460169/133110030-832bece5-6eef-4255-8e52-48497c32b61a.png)

In AGS:

![image](https://user-images.githubusercontent.com/8460169/133112263-450a9119-499a-4048-a20d-d14b541c2a5f.png)

![image](https://user-images.githubusercontent.com/8460169/133112473-6ab44113-bd64-4704-9ac4-856d91649883.png)

![image](https://user-images.githubusercontent.com/8460169/133112612-b29f6027-3e25-4801-8c2c-d154f7e8fb31.png)

![image](https://user-images.githubusercontent.com/8460169/133112802-225e08bc-d5db-4ec2-b75f-9cd31887fe98.png)

![image](https://user-images.githubusercontent.com/8460169/133113333-bdb39bb8-29d2-461e-8b15-a5aec258a1b7.png)

![image](https://user-images.githubusercontent.com/8460169/133113539-7606b0ed-d57d-4476-84d7-715e8c348525.png)

etc.

### Assemblies affected

Microsoft.OData.Core 7.9.1

### Reproduce steps

Create an app with an endpoint that uses the ODataWriter to write a resource set response with a large number of entities (eg. [this experiment](https://github.com/habbes/experiments/tree/master/ODataWriterVsSystemTextJson)). Run a memory profiler against your app (e.g. the VS .NET Object Allocator Tracking Tool) then execute the endpoint with the profiler running, and check the allocation data compiled by the profiler during the request.

### Expected result

Less number of allocations (0 ideally)

### Actual result

Excessive number of allocations

### Additional detail

@joaocpaiva @Sreejithpin  @mikepizzo

**Comment by chrisspre** [comment]
> A lot of `Enumerator` instances are getting allocated. This is due to using `foreach` and LINQ against `IEnumerable`s on hot paths.

This in itself is not a problem and I am worried we are overcorrecting. If the Enumerator gets created without a need for it or in a tight loop, yes that is a problem. But Enumerables have far more benefits than the cost of an allocation.

> 
> In cases where the collection provides a cheap way to get the count and has cheap random access (e.g. `List<T>` and arrays) we could consider using simple `for` loops and accessing elements by index directly. It would probably make the code less readable/elegant, but the savings would add up to > 1% allocation savings in AGS.

Allocation's in itself are not a problem. (a webserver (where our library typically runs) frequently allocates large amounts for a memory during a request) to many allocations are a problem. 
 
> Here are some of the "hot" loops we could consider optimizing:
> 
> * `JsonLightInstanceAnnotationWriter.WriteInstanceAnnotations(IEnumerable<ODataInstanceAnnotation>, InstanceAnnotationWriteTracker, bool, string)` has a `foreach` loop that's used on `List<T>` instances

Woudl suggest to implement a benchmark for the before and after .

> * `ODataJsonLightResourceSerializer.WriteResourceEndMetadataProperties(IODataJsonLightWriterResourceState, IDuplicatePropertyNameChecker)`: this function calls `actions.Any()` and `functions.Any()`, calling `Any()` causes the `List<T>.GetEnumerator()` to be called. I don't completely understand this because from the `Enumerable.Any` [source code](https://source.dot.net/#System.Linq/System/Linq/AnyAll.cs,11), it's not supposed to call `GetEnumerator` if the `IEnumerable<T>` also implements `ICollection<T>`, which `List<T>` does, in such cases it's supposed to check `Count != 0`.

I would also expect the optimized code path here but it depends of course if the runtime type is truely implementing ICollection

> * `Edm.ExtensionMethods.FindVocabularyAnnotations(IEdmModel, IEdmVocabularyAnnotatable)` has a `foreach` loop.
> * `ODataWriterCore.AppendEntitySetKeySegment(ODataPath, bool)` has a `foreach (IEdmStructuralProperty property in currentEntityType.Key())` loop
> * `ODataPath.ctor(IEnumerable<ODataPathSegments)` (the constructor) passes the segments `IEnumerable` to the `List` constructor, the `List` constructor iterates over the collection to add the elements to the list. Not sure if this can be optimized easily.

The problem here is not that Enumerables are used but the fact that the "Find" method has to iterate through the list. 
If we could build an index (probably an Ilookup) for the Annotations with the annotation term as the key that would speed that up. problem is that the underlying EdmModel can still change and I am not sure if we have an equality comparer for annotation terms

**Comment by ificator** [comment]
The allocation-on-enumeration issue isn't `foreach`, but rather the fact that an abstraction is used. If `WriteInstanceAnnotations` accepted `List<ODataInstanceAnnotation>` there would be no allocation, because `List.GetEnumerator` returns a struct. It's actually the boxing of that struct that's generating the allocation you're seeing.

I think changing the parameter type is the best solution if it's possible, because it's a pattern that doesn't require boiler plate code copied and pasted around the place that special cases `IList<T>` for enumeration (as much as I dislike C/C++ macros this is a place where they'd have been somewhat useful).
