### ISSUE TITLE
Function response with parameter has no meta data

### ISSUE THREAD

**Issue by Robelind** [OData/odata.net#2268]
When calling an unbound function with a parameter, the response doesn't contain any OData meta data.

### Assemblies affected

Microsoft.AspNetCore.OData 8.0.4

### Reproduce steps
```
public class TestA
{
    public int Id { get; set; }
    public string Value { get; set; }
}

[HttpGet("api/Test(parameter='{parameter}')")]
public IActionResult Test([FromODataUri] string parameter)
{
    return(Ok(new TestA {Id = 1, Value = "Test"}));
}

builder.Function("Test").Returns<TestA>().Parameter<string>("parameter");

http://localhost:53205/api/Test(parameter='Test')

```

### Expected result

_{"@odata.context":"http://localhost:53205/api/$metadata#Test.TestA","Value":"Test","Id":1}_

### Actual result

_{"value":"Test","id":1}_

**Comment by xuzhg** [comment]
@Robelind 
The single quote in `[HttpGet("api/Test(parameter='{parameter}')")]` is not required for OData template.

If you change that as `[HttpGet("api/Test(parameter={parameter})")]` by removing single quote, it should work.

Since OData doesn't need a single quote, it thinks it's not a valid OData route template. So, let it go and go into normal ASP.NET Core routing.

**Comment by gathogojr** [comment]
@Robelind Please confirm whether the response provided above addressed the issue

**Comment by Robelind** [comment]
Yes, the single quotes were the problem.
