### ISSUE TITLE
OData library 8.0.4 does not add the control information property for open types. (using odata.metadata=minimal accept header value) 

### ISSUE THREAD

**Issue by BenAlfasi** [OData/odata.net#2294]
Hi, 

Note - we get the following Accept header: accept=application/json;odata.metadata=**minimal**)
When we get the full accept header (accept=application/json;odata.metadata=**full**), we have control information for all properties (except strings of course).

Example:

Created simple Open type:

public class HuntingRowResults
    {
        public IDictionary<string, object> DynamicProperties { get; set; }
    }

when I'm adding int64 to the dictionary I'm getting the following response: 

{
            "EmailClusterId": 2629759514
}

But the expected response should be: 

{
            "EmailClusterId@odata.type": "#Int64",
            "EmailClusterId": 2629759514
}

Thanks,
Ben

**Comment by mikepizzo** [comment]
This is strange -- we have code and tests that are supposed to add control information for dynamic properties. 

For example, see [UndeclaredIntShouldWriteTypeName](https://github.com/OData/odata.net/blob/master/test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightPropertySerializerTests.cs#L323-L326).

It does appear, if the caller explicitly sets the TypeAnnotation on the ODataValue to a TypeAnnotation with a null type name, then the expected behavior is not to write the annotation (see test [here](https://github.com/OData/odata.net/blob/master/test/FunctionalTests/Microsoft.OData.Core.Tests/JsonLight/ODataJsonLightPropertySerializerTests.cs#L370-L375)).

Could the issue in WebAPI be that WebAPI is explicitly setting the TypeAnnotation to a non-null value with a null type name?

**Comment by BenAlfasi** [comment]
Hi @mikepizzo , I can see your tests, but it still doesn't works in my Web API.
I don't understand your last comment about WebAPI explicitly setting null type name..,
I would love to make a quick call and show you my repro (I already showed it on a call to Sam few weeks ago).
Thanks,
Ben

**Comment by xuzhg** [comment]
@BenAlfasi Can you try this nightly: Microsoft.AspNetCore.OData.8.0.6-Nightly202201312349

For how to setup visual studio and config the nightly, you can refer to: https://github.com/OData/AspNetCoreOData#34-nightly-builds

**Comment by BenAlfasi** [comment]
@xuzhg, see my response at https://github.com/OData/AspNetCoreOData/issues/457 
I think we can close this issue because its duplicate (created here and above by my mistake)

**Comment by gathogojr** [comment]
Addressed in https://github.com/OData/AspNetCoreOData/issues/457
