### ISSUE TITLE
Unable to retrieve vocabulary annotations for operation parameters in CSDL

### ISSUE THREAD

**Issue by irvinesunday** [OData/odata.net#2337]
Trying to retrieve the vocabulary annotations for operation parameter elements using either `EdmModel.FindDeclaredVocabularyAnnotations(<element>)` or `EdmModel.FindVocabularyAnnotations(<element>)` yields no result.

### Assemblies affected

**Microsoft.OData.Edm** `v7.10.0`
### Reproduce steps

Try to get the vocabulary annotations for a given parameter element, e.g.

![image](https://user-images.githubusercontent.com/40403681/157036480-1e361662-aecd-4d4d-b47a-fc5ffe43d611.png)

using either of the below calls:

```
IEnumerable<IEdmVocabularyAnnotation> annotations = context.Model.FindDeclaredVocabularyAnnotations(edmParameter);
IEnumerable<IEdmVocabularyAnnotation> annotations2 = context.Model.FindVocabularyAnnotations(edmParameter);
```
where `edmParameter` = appScopeId (of type `IEdmOperationParameter`)

### Expected result

The in-line vocabulary annotation `Org.OData.Core.V1.OptionalParameter` should be retrieved.

### Actual result

No vocabulary annotation is retrieved.

### Additional detail

CSDL used: https://raw.githubusercontent.com/microsoftgraph/msgraph-metadata/master/clean_beta_metadata/cleanMetadataWithDescriptionsAndAnnotationsbeta.xml

**Comment by xuzhg** [comment]
@irvinesunday It's tricky implementation and by design.

Actually, you cannot get that annotation value because it's never generated.

The implementation for this is:
- Reading: If the parameter has OptionalParameter vocabulary annotation, we convert it to IEdmOptionalParameter from IEdmOperationParameter.
- Writing: if the parameter is IEdmOptionalParameter, we write the annotation for this parameter.

So, for your perspective, you don't need to 'retrieve' the vocabulary annotation, you can test the IEdmOperationParameter object using IEdmOptionalParameter. If the parameter implements the IEdmOptionalParameter, you can get more info/data from this interface. 

Hope it can help.

**Comment by gathogojr** [comment]
@irvinesunday Please confirm if the optional parameter is the only vocabulary you're interested in?

**Comment by irvinesunday** [comment]
Yes @gathogojr, this is the only vocabulary annotation I'm interested in. @xuzhg recommendation works. Thanks!
