### ISSUE TITLE
incorrect case for PublicAPI folder

### ISSUE THREAD

**Issue by dweeden** [OData/odata.net#2406]
The last three letters of the path odata.net/src/Microsoft.OData.Edm/PublicApi should be upper case so it compiles on Linux without generating a bunch of RS0016 errors

### Assemblies affected

Current version of Microsoft.OData.Edm

### Reproduce steps

Pull source onto a Linux machine and try to compile Microsoft.OData.Edm project

### Expected result

It would compile

### Actual result

It doesn't compile and yields a whole slew of RS0016 errors as it can't find the shipped and unshipped API files

**Comment by dweeden** [comment]
Renaming it to PublicAPI fixes the problem for me locally

**Comment by AntiGuideAkquinet** [comment]
@corranrogue9 
It seems to me like changing the `Microsoft.OData.Edm.csproj` like this
```
// DELETE
<AdditionalFiles Include="PublicAPI/$(TargetFramework)/PublicAPI.Shipped.txt" />
<AdditionalFiles Include="PublicAPI/$(TargetFramework)/PublicAPI.Unshipped.txt" />
// INSERT
<AdditionalFiles Include="PublicApi/$(TargetFramework)/PublicAPI.Shipped.txt" />
<AdditionalFiles Include="PublicApi/$(TargetFramework)/PublicAPI.Unshipped.txt" />
```
would solve the issue. Due to the dependency on VS2019 Enterprise in the build scripts I can't verify this tough.
This issue seems like it would have a lot of impact to users building in CI pipelines or on Linux host machines.
