### ISSUE TITLE
The ConstantNode from CollectionConstantNode returns type full name in LiteralText property

### ISSUE THREAD

**Issue by SamGuoMsft** [OData/odata.net#2607]
@xuzhg , as we discussed, The ConstantNode from CollectionConstantNode returns type full name in LiteralText property.
Here is the snapshot:
![image](https://user-images.githubusercontent.com/40610249/214758286-0268c209-dc61-44d5-b209-771cf7d906dc.png)

### Assemblies affected

*Which assemblies and versions are known to be affected e.g. OData .Net lib 7.x*

### Reproduce steps

*The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.*

### Expected result

*What would happen if there wasn't a bug.*

### Actual result

*What is actually happening.*

### Additional detail

*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by xuzhg** [comment]
@SamGuoMsft The problem is from this line code:

https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/UriParser/SemanticAst/CollectionConstantNode.cs#L57

It calls `ToString` for the item and takes that as literal. we don't overwrite ODataEnumValue.ToString(), so it outputs the type name.

The fix could be:
1) Not set the literal for the item. Keep it as null,  (Because you can get the collection literal, each item literal is included in the collection literal)

2) Call convert the item into the URI literal. we can call '[ConvertToUriLiteral](https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Core/Uri/ODataUriUtils.cs#L114), but we don't have the model in the CollectionConstantNode constructor. It only works for primitive values.

3) or simply override ToString for ODataEnumValue or other OData value classes. It only fixes parts and this output could be not the same as the original literal. 

Let me draft the fix based on  # 3.
