### ISSUE TITLE
OData Client Request Pipeline not working in Post scenario

### ISSUE THREAD

**Issue by xuzhg** [OData/odata.net#272]
It seems the bug https://github.com/OData/odata.net/issues/134 is not fixed thoroughly. Thanks.

**Comment by halipourian** [comment]
After some investigation through code I think I've found out the cause of the problem. The solution provided by @AdamCaviness uses EdmStructuredSchemaElements property on ClientEdmModel, which is being set when the first TypeResolver is being constructed, and when does a TypeResolver being constructed? When a RequestInfo is being constructed. And guess what, a RequestInfo is only (actually it's not the only place, read on and you'll see) being constructed when we are trying to get some kind of result from the service. That's why the solution does not work in a Post scenario **if nothing has retrieved from the service yet**.

### Workaround
So if we try to get any kind of result from the service before any Post requests, everything works as expected!  But that's not OK! I mean it's an extra call to service to workaround a bug! My second workaround is to set that property using reflection in the DataServiceContext constructor after getting ServiceModel (like by calling Format.UseJson()).
```
var serviceModel = (IEdmModel) typeof (DataServiceClientFormat).GetProperty("ServiceModel", BindingFlags.Instance | BindingFlags.NonPublic).GetValue(this.Format);
var clientModel = typeof (DataServiceContext).GetProperty("Model", BindingFlags.Instance | BindingFlags.NonPublic).GetValue(this);
clientModel.GetType().GetProperty("EdmStructuredSchemaElements", BindingFlags.Instance | BindingFlags.NonPublic).SetValue(clientModel, serviceModel.SchemaElements.ToList());
```

As another workaround I've found another way (by searching through code) to create the very first RequestInfo without reaching for service by calling Serializer.GetKeyString method. It doesn't mean anything to call this method after getting ServiceModel. It just creates an instance of the RequestInfo which creates the very first instance of TypeResolver and that will solve our issue!
```
Serializer.GetKeyString(this, new Dictionary<string, object> {{"Dummy", 0}});
```

### Suggested solution
I don't think the best place to set this property is in the TypeResolver's constructor. Maybe it would be better to set it after we load the ServiceModel (In the DataServiceClientFormat.ServiceModel getter after we call LoadServiceModel, or after we call UseJson overload with the serviceModel parameter). But surely I'm not an expert in this library like you guys. 

At the end I must say that I'm really thankful for all the efforts you guys are putting in to this project.
