### ISSUE TITLE
Adding NavigationTarget(AddNavigationTarget) should be optional for non-containment navigation property

### ISSUE THREAD

**Issue by sabyabr** [OData/odata.net#273]
ODataUriParser.ParseUri should let setting NavigationTarget(AddNavigationTarget) optional for non-containment navigation property

Basically, the below code in http://odata.github.io/odata.net/#02-03-define-entity-relations should be optional

_customerSet.AddNavigationTarget(_friendsProperty, _customerSet);

**Comment by congysu** [comment]
Related issue: https://github.com/OData/odata.net/issues/295

**Comment by lewischeng-ms** [comment]
Hi @sabyabr This issue has been fixed in  https://github.com/OData/odata.net/commit/74969d976eb913fa6ce30cd992943750af6f1cb2. Please see the following test case for reference: https://github.com/OData/odata.net/blob/master/test/FunctionalTests/Tests/DataOData/Tests/OData.TDD.Tests/Writer/JsonLight/ODataJsonLightFeedWriterTests.cs
