### ISSUE TITLE
Using Odata Linq client with Parameters

### ISSUE THREAD

**Issue by vasicvuk** [OData/odata.net#2815]
We are using Microsoft.OData.Client library for generating `filter` queries based on models we have in the client app, and then on the server side we use queries to filter the data.

Since the server is the one providing parameters we are looking for an option to still build query on the client side with LINQ but place some parameters that will be replaced by the server.

This is easy to implement when the property is a string, but we also have enums, DateTime, numbers, and similar.

Do you have any suggestions to do this with the library? Maybe to write some extension for it?

**Comment by gathogojr** [comment]
Thank you @vasicvuk for reporting this issue. Can you provide an illustration of how you scenario looks like so that we can understand your ask better? For example, illustrate for us how you are able to make it work when the property is a string. In addition, how your service is able to replace the parameter with actual values.

**Comment by gathogojr** [comment]
Insufficient details to repro the reported issue
