### ISSUE TITLE
Grouping by a nested dynamic property differs from grouping by a nested standard property

### ISSUE THREAD

**Issue by clemvnt** [OData/odata.net#2963]
Hello,

I have a case where I want to group by a nested dynamic property.

The result is not the same as when I group by a nested standard property.

Is there an explanation for this or is it a bug?

**Assemblies affected**

Microsoft.AspNetCore.OData 8.2.5

**Reproduce steps**

1. Clone the repository : https://github.com/clemvnt/ODataGroupByNestedDynamicProperty
2. Run

**Actual result**

1. `/customers` => OK
2. `/customers?$apply=groupby((Address/City))` => OK
```json
[
    { "Address": { "City": "City 2" } },
    { "Address": { "City": "City 1" } }
]
```
3. `/customers?$apply=groupby((Address/DynamicCity))` => NOK
```json
[
    { "DynamicCity": "City 2" },
    { "DynamicCity": "City 1" }
]
```

**Expected result**

I would expect the following result for the third query :
```json
[
    { "Address": { "DynamicCity": "City 2" } },
    { "Address": { "DynamicCity": "City 1" } }
]
```

**Comment by gathogojr** [comment]
@clemvnt Thank you for reporting this issue and for the thorough investigation. To answer your questions:
- The fix looks good. Great work!
- From a behaviour perspective, this would be considered a breaking change. However, we'd be ready to make a concession here and allow this change since what we're writing to the wire is actually invalid. I'd hate to imagine that anyone is taking a dependency on this invalid payload
- We have transferred the issue to the right repo

Kindly create a pull request and add some tests. We'll be happy to review.
Thanks
