### ISSUE TITLE
Odata returns generic type error when enum is a key

### ISSUE THREAD

**Issue by biboller** [OData/odata.net#2964]
Our project uses enums as keys. For example we use weekday as a key here.
 
<img width="860" alt="image" src="https://github.com/OData/odata.net/assets/29041596/78afd4d4-b7fa-46e8-85f6-9c71e5119cc1">

This wouldn’t be a problem expect that when getting the data from odata the mapping fails with the following error:

           This operation is only valid on generic types.

### Assemblies affected

Microsoft.OData.Core 7.x

### Reproduce steps

Add an enum as a key

### Expected result

We expect enum's to be useable as keys

### Additional detail

In the file OdatatypeInfo.cs in the method GetKeyProperties() we found that the program assumes that the property should be generic type and afterwards checks if it is an enum. 

 
<img width="1170" alt="image" src="https://github.com/OData/odata.net/assets/29041596/51493f7e-e151-45b3-b77d-49c8900a9f25">

We think the order should be changed in the if statement and the IsEnum() should be inverted.  

Are we over looking something? We tried getting, updating and posting data with this change. Which all worked without problem

<img width="1183" alt="image" src="https://github.com/OData/odata.net/assets/29041596/7a46f6b1-1744-48a3-85b9-9ad3875288ab">

**Comment by mikepizzo** [comment]
Yes, we should support enums as keys.

Note: the code shown above as the current logic in the first block is slightly different than what I see in the repo.

In the repo, the conditional check is:

```c#
                if (!PrimitiveType.IsKnownType(key.PropertyType) && !(key.PropertyType.GetGenericTypeDefinition() == typeof(System.Nullable<>) && key.PropertyType.GetGenericArguments().First().IsEnum()))
```

which is different than above reported code in that:
1) the IsEnum check is on keyProperty.PropertyType*GetGenericArguments().First()*.IsEnum(), rather than keyProperty.PropertyType.IsEnum()
2) the IsEnum check is grouped with the GetGenericTypeDefinition() check rather than a separate check

I suspect the reason that the fixed code doesn't throw is not because of ordering, or even grouping, but because it doesn't call GetGenericArguments.

I'm not sure the rationale behind the existing logic that would make us think that an unknown type must be generic (or why we specifically check for an enum if it is), but if we don't know for sure that key.PropertyType is generic we should check IsGenericType before calling GetGenericTypeDefinition or GetGenericArguments.

**Comment by kyleweishaupt** [comment]
I'm also encountering the same issue when attempting to access the Microsoft Business Central API through OData V4. We're using the latest Microsoft.OData NuGet packages, 7.21.1. Any attempt to enumerate a collection with an enum key returns the error about generic types, even when trying to project to a new class.

**Comment by nmushovic** [comment]
To expand on the above, it looks like the Business Central API converted quite a few string to Enums. The ItemReference class uses an Enum as a key field and we're getting the error in GetKeyProperties().

![image](https://github.com/OData/odata.net/assets/1312096/b8caeabf-481e-4790-8d69-1e75cc4f8248)

**Comment by biboller** [comment]
@mikepizzo Yes the problem seems to be that GetGenericTypeDefinition is called too early. The code should accept simple types and enums as valid keys and reject generic types. So changing the ordering of the if statement ensures that GetGenericTypeDefinition isn't called if the key is an enum. Can we contribute on this issue by creating a pr to fix this?

**Comment by MikkelGlerup** [comment]
Any news on this? 
We're having the same problem when using Odata together with Business Central

**Comment by nmushovic** [comment]
We used a work around by selecting odatakeys and not selecting the enum key fields. https://www.cloudfronts.com/blog/d365-business-central/using-odatakeyfields-for-fetching-records-in-business-central-web-services/

**Comment by MikkelGlerup** [comment]
Sadly that isn't going to work for me. 
I'm getting the error when running this code 
` var linesQuery = new DataServiceCollection<MtSalesInvoiceLine>(_mtApiContext.MtSalesInvoiceLines.AddQueryOption("$expand", "dimensionSetLines").Where(s => s.DocumentId == salesOrder.Id));
`

There's an enum key field somewhere in the hierarchy.

Will update when I find a solution though

**Comment by MikkelGlerup** [comment]
Found out my error was due to breaking changes being introduced on Business Centrals side with version "24.1.18927.19282". Running the same code towards an Business Central Cloud environment running "24.0.16410.17628" succeeds.

**Comment by nmushovic** [comment]
@MikkelGlerup , do you have a link to the breaking change?

**Comment by MikkelGlerup** [comment]
@nmushovic I made my own issue and gave it more details [here](https://github.com/OData/odata.net/issues/3003)

**Comment by martinfbluesoftcz** [comment]
Hello, can someone to aprove this fix: https://github.com/OData/odata.net/pull/3013
It is critical because our app which communicates with MS Bussiness Central does not work after new API definition with enums was updated.
@gathogojr @habbes @xuzhg @ElizabethOkerio @paulodero 
Thank you very much.

**Comment by mikepizzo** [comment]
See my comment in the issue.

I'm not sure why we allow nullable<enum>, since keys have to be non-nullable, but changing that now would be a breaking change.

However, the proposed change allows *any* nullable<T>, which makes the issue much worse.

I've suggested a change to support enums and nullable<enum>, but not other nullables. Please take a look.

Thanks,

-Mike

**Comment by martinfbluesoftcz** [comment]
@mikepizzo It looks fine now.

**Comment by martinBluesoft** [comment]
Do you know when a new version with a fix for this bug will be released?
