### ISSUE TITLE
EdmTargetPath does not get parsed correctly if it contains a collection-valued NavigationProperty

### ISSUE THREAD

**Issue by garethj-msft** [OData/odata.net#2969]
EdmTargetPaths cannot be created by parsing from paths such as the following:
`NS.Container/Singleton/CollectionNavProp1/CollectionNavProp2`

This prevents such paths being used as the target of annotations.

### Assemblies affected

OData .Net lib 7.21.1

### Reproduce steps

``` csharp
 string inputFile = args.Length > 0 ? args[0] : "";

 string csdl = File.ReadAllText(inputFile);
 IEdmModel model = CsdlReader.Parse(XElement.Parse(csdl).CreateReader());

 foreach (var annotation in model.VocabularyAnnotations)
 {
     if (annotation.Target is not IEdmTargetPath path) continue;
     var explicitSegmentCount = path.Path.Split('/').Length;
     if (explicitSegmentCount != path.Segments.Count)
     {
         Console.WriteLine($"Path '{path.Path}' has {explicitSegmentCount} segments, but {path.Segments.Count} segments are specified.");
     }
 }
```

### Expected result

Target path parsed correctly.

### Actual result

Target path's `Segments` collection stops at first collection-valued navigation property.

**Comment by mikepizzo** [comment]
For Annotation targets (and a few other places like navigation property binding paths) we use a *model path*, rather than an *instance path*.  Model paths are a path through model elements and do not include instance data (most notably, keys), where-as instance paths must be valid urls in data space, thus collections must be followed by cast segments or keys.

So, in this case, we should allow a segment representing a collection-valued model element followed by another segment representing a collection-valued model element.

A discussion of model versus instance paths can be found [here](https://docs.oasis-open.org/odata/odata-csdl-xml/v4.02/csd01/odata-csdl-xml-v4.02-csd01.html#PathExpressions)
