### ISSUE TITLE
Enum value not parsed for `in` query operator

### ISSUE THREAD

**Issue by XVincentX** [OData/odata.net#3120]
| Request URL | Forwarded URL |
|--------|--------|
| `/identityProtection/RiskyUsers?$filter=riskLevel eq 'low'`  | `identityProtection/riskyUsers?$filter=riskLevel+eq+Microsoft.IdentityProtectionServices.riskLevel'low'` |
| `/identityProtection/RiskyUsers?$filter=riskLevel in ('low')` | `/identityProtection/riskyUsers?$filter=riskLevel+in+('low')` |

ODL doesn't parse the value as Enum for the `in` case.

**Comment by xuzhg** [comment]
@XVincentX 

### Filter using binary operator
`http://~?$filter=Shape eq 'Rectangle'`

```txt
BinaryOperatorNode
  |-- SingleValuePropertyAccessNode: Shape
  |-- ConstNode: Fully.Qualified.Namespace.NonFlagShape , Literal: 'Rectangle'
```

### Filter using in operator

`http://~?$filter=Shape in ('Rectangle', 'Triangle') `

```
InNode
  |-- SingleValuePropertyAccessNode: Shape
  |-- CollectionConstantNode:
    |-- ConstNode: Fully.Qualified.Namespace.NonFlagShape , Literal: Rectangle
    |-- ConstNode: Fully.Qualified.Namespace.NonFlagShape , Literal: Triangle
```

So, It seems OData can successfully parse the enum value in the 'in' operator. Of course, same as the binary operator, it outputs the 'ConstantNode' for the potential enumn literal. Good news is that the ConstNode type gives the correct type information.

So, I don't know where you get the 'Forwarded URL'. What doesn't it mean and where do you get this URL?

**Comment by xuzhg** [comment]
> > I don't know where you get the 'Forwarded URL'. What doesn't it mean and where do you get this URL?
> 
> @xuzhg That is basically the URL that gets forwarded to the workload from the Aggregator Service

Then, I think it's a gap within AGS.

**Comment by syprieur** [comment]
@xuzhg: concern is observed inconsistent behavior between 'eq' and 'in' (processing of single-item vs collection).
It may or may not be due to specific URI resolvers (e.g. StringAsEnum).

Could you please try this repro?

1. http://~?$filter=Shape eq 'EnumValueWhichDoesNotExist'
2. http://~?$filter=Shape in ('EnumValueWhichDoesNotExist')

With AGS Uri resolver, we get:
1. Microsoft.OData.ODataException: 'The string 'EnumValueWhichDoesNotExist' is not a valid enumeration type constant.'
2. InNode
  |-- SingleValuePropertyAccessNode: Shape
  |-- CollectionConstantNode:
    |-- ConstNode: Fully.Qualified.Namespace.NonFlagShape , Literal: **EnumValueWhichDoesNotExist**

**Comment by syprieur** [comment]
In the first case, exception is thrown by the StringAsEnumResolver, in method:
`PromoteBinaryOperandTypes(BinaryOperatorKind binaryOperatorKind, ref SingleValueNode leftNode, ref SingleValueNode rightNode, out IEdmTypeReference typeReference)`

Note that ODataUriResolver doesn't seem to have an overload for CollectionNode instead of SingleValueNode as rhs. That may be why the latter case doesn't throw.

**Comment by xuzhg** [comment]
@syprieur @XVincentX If my understanding is correct, please review the PR at #3125.

**Comment by rpallares** [comment]
Thx for that issue and fix.  
I believe there's the same issue client side https://github.com/OData/odata.net/issues/2778

Is there any chance to have a fix for it also?

Thx
