### ISSUE TITLE
Filter/sort on Open Types

### ISSUE THREAD

**Issue by congysu** [OData/odata.net#354]
Query option parser’s support to dynamic properties:
-   Supported: Select
-   Not supported: Filter, Expand
  - Filter: Cannot get type information from model.  How does Exchange determine a dynamic property’s type in an request uri?
  - Expand: Dynamic navigation property is not supported.

**Comment by lewischeng-ms** [comment]
Confirmed that $select, $filter and $orderby on open types are already supported. Dynamic properties appeared in $filter and $orderby are parsed as `OpenPropertyAccessNode`. $expand on open types is **not supported** yet.

SWAG for this task
 - **Protocol**: According to [OData spec](http://docs.oasis-open.org/odata/odata/v4.0/errata02/os/complete/part2-url-conventions/odata-v4.0-errata02-os-part2-url-conventions-complete.html#_Toc406398093): *Dynamic properties can be used in the same way as declared properties. If they are not defined on an instance, they evaluate to null.*
 - **Design**: **1 week** on prototype for the most important cases. The design could be mainly about `SelectExpandBinder.GenerateExpandItem`. Maybe we have to introduce a new segment type `OpenNavigationPropertySegment` to replace the original `NavigationPropertySegment` in `ODataExpandPath`. We also need to figure out what the target navigation source should be given the navigation property is dynamic. Thus we need to evaluate the impact on all nested query options inside a $expand clause since all of them have no navigation target info now.
 - **Code**:
 - **Test**:
 - **E2E**:
 - **Doc**:

**Comment by johnrulon** [comment]
@lewischeng-ms @LaylaLiu Any update on this bug around Dynamic Properties not working in the same way that declared properties do? (in that they can't be used with Expand)

**Comment by phatcher** [comment]
@lewischeng-ms Can we get an update please, I'm having to postpone using open types because of this issue.

**Comment by ElizabethOkerio** [comment]
Related to: https://github.com/OData/WebApi/issues/811
