### ISSUE TITLE
[T4] Support TypeDefinition

### ISSUE THREAD

**Issue by LaylaLiu** [OData/odata.net#359]
OData client code generator does not support metadata containing TypeDefinition, which makes it impossible to generate a client proxy for metadata which now contains a TypeDefinition:
  <TypeDefinition Name="DateTime" UnderlyingType="Edm.String" />

**Comment by sab39** [comment]
I just got bitten by this bug and I'm considering having a go at a fix for it. If I'm understanding the code correctly, it'd involve making changes to `ODataT4CodeGenerator.ttinclude`, specifically:

* In the `WriteNamespace` method, add handling for `IEdmTypeDefinition` in the `ISchemaType` loop to call `WriteTypeDefinition()`
* Add the `WriteTypeDefinition` method and implement it for C# and VB
* In the `Utils.GetClrTypeName` method, add handling for `IEdmTypeDefinition`
Is that all, or am I missing some other places that would need fixing?

I'm not sure what the generated code might want to look like. I was thinking something along the following lines (in C#), but it gets complicated once you start thinking about what operators to lift from the underlying type, as well as implementing things like `IComparable<T>`, `IEquatable<T>`, `GetHashCode()`, `Equals()`, `ToString()`, and whether the generated type should be a `class` rather than a `struct` if the underlying type is `Edm.String`.

    public struct [[typename]] {
      private readonly [[underlyingType]] value;
      public [[underlyingType]] Value { get { return value; } }
      public [[typename]]([[underlyingType]] value) {
        this.value = value;
      }
      public static implicit operator [[typename]]([[underlyingType]] value) {
        return new [[typename]](value);
      }
      public static explicit operator [[underlyingType]]([[typename]] t) {
        return t.Value;
      }
      public static bool operator==([[typename]] a, [[typename]] b) {
        return a.Value == b.Value;
      }
      ... etc.
    }

An alternative simpler approach would be to skip `WriteTypeDefinition` entirely and just have `Utils.GetClrType` return the CLR type for the underlying primitive type directly.

Thoughts?

**Comment by sab39** [comment]
I had a go at implementing the simple version, where type definitions are just mapped directly to the underlying property, and it seems to work. My code changes are [here](https://github.com/OData/odata.net/compare/ODataV4-6.x...sab39:sab39-type-def-support). Would a pull request along these lines be considered?

**Comment by AlanWong-MS** [comment]
Hi @sab39, first off, thank you so much for your interest in helping to make the product better. Apologies for the late response as there have been resource shuffling over the months and re-prioritizations. We're currently reviewing our PRs and issues; please do open a pull request with these lines and we'll take a look. Thanks again!

**Comment by mikepizzo** [comment]
Hi @sab39.  As Alan says, we'd love to get your PR for this change.

In the meantime, according to our [triage guidelines](https://github.com/OData/WebApi/blob/master/.github/ISSUE_TRIAGE.md), I am closing this issue rather than leaving it open/inactive in order to make sure you are notified and in hopes that you can provide a PR.

Looking forward to your PR!

Thanks for your continued interest in the OData libraries.
