### ISSUE TITLE
Built-In Functions to be customized

### ISSUE THREAD

**Issue by YogiBear52** [OData/odata.net#378]
OData.Core has Built-In Functions like 'contains' 'endswith' 'geo.intersects' and so on. These functions are hard coded and cannot be customized or be modify.

OData lib has to be open and easy to be customized and modified by the users needs.

I suggest to add Custom Functions mechanism so the user could add,modify or override the existing pre defined built-in functions.

**Comment by brjohnstmsft** [comment]
@LaylaLiu @YogiBear52 Why aren't custom functions determined based on the EDM model? Having a global table of functions is unfortunate since in some OData services, there are multiple models in the same AppDomain and not all of them have the same set of custom functions. The global table breaks the isolation between EDM models.

**Comment by AlanWong-MS** [comment]
Per comment in #430, this issue has been resolved. Closing issue, but please feel free to continue the discussion here for any questions.
