### ISSUE TITLE
Supporting alternate key

### ISSUE THREAD

**Issue by dingeins** [OData/odata.net#55]

**Comment by shahzorkhan123** [comment]
Pull Request created by CbrooksMSFT for Alternate keys Protocol
https://github.com/OData/vocabularies/pull/9

Apart from that, the following are required changes in OData
IEdmEntityObject to have Key property, that can be used to differentiate between the property used for AlternateKey or for setting the value (In case of update scenario)

Add the following property to IEdmEntityType

    {
		// Summary:
		//     Gets the Alternate keys of the entity type 
		IEnumerable<IEdmAlternateKey > DeclaredAlternateKeys { get; }
    }

And AlternateKey as

    public interface IEdmAlternateKey : IEdmSchemaType, IEdmType, IEdmTerm, IEdmSchemaElement, IEdmVocabularyAnnotatable, IEdmElement
    {
		// Summary:
		//     Gets the structural properties of the entity type that make up the key
		IEnumerable<IEdmStructuralProperty> KeyProperties { get; }
    }

**Comment by shahzorkhan123** [comment]
Can we schedule some time to sync up on the design, so that we can plan for contribution based on the complexity.

**Comment by congysu** [comment]
@shahzorkhan123 Change to Uri parser should be sufficient.  For `~/Customers(altkey)`, parser could check if the `altkey` is an alternate key by checking the vocabulary annotation in $metadata.  Then create an AlternateKeySegment or reuse an existing KeySegment etc.

**Comment by congysu** [comment]
Link a same issue: https://github.com/OData/odata.net/issues/13

**Comment by shahzorkhan123** [comment]
In order to retrieve AlternateKeys from the Annotations stored in model, We would need to pass the model wherever the Key Resolution is required. This is leading to changes in several public interfaces like UriResolver etc. 

Eg. For UriResolver.ResolveKeys the namedValues gets resolved to Keys stored in IEdmEntityType, however the AlternateKeys information is available as an Annotation, hence we need to pass IEdmModel as an additional Property.

Similarly the usages, SegmentArgumentParser.TryConvertValues and SegmentKeyHandler donot have a Model Object for reference.

We either need to additionally store the Annotation on the EdmEntityType, or store the model in these additional parsers

**Comment by xuzhg** [comment]
Merged the PR. Thanks.
