### ISSUE TITLE
Reader Performance Regression due to undeclared property support

### ISSUE THREAD

**Issue by luoyan0517** [OData/odata.net#566]
Observed from: https://msit.powerbi.com/groups/me/reports/a4bf72f8-bcc7-45c9-9bd3-533f77ceb913/ReportSection7 

Related Changes:
e52e1cd849911b20b17470ba2e0b48b443e9b540 
fa3a8f4e519bb95a47cb809be5dfbad2862c161f

**Comment by challenh** [comment]
1. The e52e1cd  mainly have two changes affecting performance of reading *payload without undeclared property*, that have been 'reverted' by these 2 following changes:

 50ea9dd ("Use JsonWriter to re-composite the original json, instead of relying on IJsonReader.RawValue, for better performance.", 2016-06-13)
 372262b ("Use DuplicatePropertyNamesChecker to collection instance annotations, for better performance, and remove PropertyAnnotationCollector.cs.", 2016-06-27)

2. The  fa3a8f4 introduced an IMessageValidationSetting (shouldn't have hurt performance) which is also gone now.
