### ISSUE TITLE
.NET Core packages

### ISSUE THREAD

**Issue by markrendle** [OData/odata.net#568]
Now that .NET Core RC2 is out, and RTM is expected by the end of June, please will you provide compatible assemblies and NuGet packages. There are important downstream dependents (e.g. Azure Storage SDK for .NET) that cannot provide Core versions of their packages until you have shipped Core versions of yours.
### Assemblies affected

Microsoft.Data.Edm
Microsoft.Data.OData
Microsoft.Data.Services.Client
Microsoft.Spatial (is this the new name for System.Spatial?) 
### Reproduce steps

Try to create an ASP.NET Core RC2 application on CoreCLR RC2 that uses Microsoft Azure Storage.  
### Expected result

The latest Microsoft libraries on the latest Microsoft stack are the **best** choice for working with Microsoft Cloud services. 
### Actual result

The latest Microsoft libraries on the latest Microsoft stack are the **worst** choice for working with Microsoft Cloud services.

**Comment by JauernigIT** [comment]
I totally agree. OData is fundamental for many projects, that just due to this dependency cannot move to .NET Core. It should be no question and high priority to have the library on .NET Core, since it's required by a whole ecosystem.

**Comment by cohenomri** [comment]
+1

**Comment by PinpointTownes** [comment]
FWIW, the port should be relatively easy, as ODataLib is a PCL Profile 259, which is compatible with .NET Standard 1.0.

https://github.com/OData/odata.net/issues/97#issuecomment-78419596

**Comment by markdstafford** [comment]
It is definitely a high priority for us to have .NET Core support. It's more feasible at this layer (the core libraries) than it is in Web API OData. For our "official" statement at higher levels, see https://github.com/OData/WebApi/issues/229#issuecomment-194632766. For the core libraries, we can definitely put this on the roadmap sooner but at this point we are completely focused on a breaking changes release we are planning for late June/early July. That release should have improved performance, dramatically improved extensibility (via dependency injection), and something called "untyped JSON" (see #248). I would think we could slate .NET Core support in the core libraries after that release. An estimated (not a promise :)) timeframe would be late July.

If someone in the community has the ability to send us a PR, it's certainly possible for us to include that in the upcoming release (7.0.0). We would want to base the work on the https://github.com/OData/odata.net/tree/ODataV4-7.x branch.

**Comment by am11** [comment]
@markdstafford, could you please review #591? With the released package of odata, we cannot use Azure Storage package on Unix where mono is unavailable. With the assembly produced by the said PR, the dependency on Mono PCL disappeared (emerged as a pure NetStandard assembly).

---

Note that the full framework assemblies continue to build with existing `csproj` files. At later point, all the framework monikers can be incorporated in the `project.json`s.

Alternatively, we can wait for the convergence as the future plan of .NET team is to adopt back the csproj in upcoming version of build system, where csproj will be able to target and build multiple frameworks in one go. Reference: https://blogs.msdn.microsoft.com/dotnet/2016/05/23/changes-to-project-json/

> The first wave of this change will happen in the Visual Studio “15” RTM: when opening any .NET Core project in Visual Studio, it will automatically convert from .xproj to .csproj, moving the assets from the project.json file into configuration files and the .csproj file. We will also provide a tool for converting applications using the .NET command line tools as well.

---

In the meanwhile, we can safely use xproj / project.json to target NetStandard.

Thanks. :)

**Comment by GuardRex** [comment]
@markdstafford 

Please :pray: see if you can move on https://github.com/OData/odata.net/pull/591 (or something like it for NETStandard) so that (for example) `WindowsAzure.Storage` can consume packages without `imports` when they make a move for GA. Packages incompatible with .NET Core RTM are holding up community developers (like me! :smile: ). I'm speaking specifically about ...
```
Microsoft.Data.OData 5.6.4
Microsoft.Data.Services.Client 5.6.4
System.Spatial 5.6.4
Microsoft.Data.Edm 5.6.4
```
... and any dependencies of them.

**Comment by advancedrei** [comment]
Everyone,

I'm just an outside contributor, so I'm not speaking for the team right now. But you should probably be aware that the OData team is small, and being pulled in a several different directions right now. As Mark mentioned, they will have support for it soon, but Microsoft gave a lot of other internal teams a lot of extra work by having to support 2 platforms, so you're going to have to be patient.

The .NET team barely just got their crap together in time to get .NET Core shipped. The reality is, you're going to be held up by package dependencies for the next several months. If it's not this package, it's going to be something else. The rest of the ecosystem is going to need time to catch up. It's like 2000 all over again with .NET 1.0.

If you're building something where your job depends on shipping, and you're building on .NET Core, you should probably adjust your strategy if you want to keep your job. That's the advice I have given several other companies in the same predicament.

Sorry if that is not what you want to hear. But I do hope it helps set expectations.

**Comment by markdstafford** [comment]
Thanks for the pings @am11 and @GuardRex. As @advancedrei mentioned, we do happen to have quite a bit on our plate right now but this definitely makes sense to include in 7.x. My main concern is doing it the right way. The .NET team shipped only the framework for a reason - the tooling and build systems need more time to bake. Given our resource constraints, we try to minimize rework.

Re: timing, I would ask that we be able to ship 7.0.0 before focusing on .NET Core support. We expect 7.0.0 to land in the next few weeks - we're working on the final issues. Once we have 7.0.0 shipped, I think .NET Core support is the next highest priority, followed closely by navigation properties on complex types (for the two people in the world who understand what that meant :)). Both of those features should be included in 7.1.0, which I think will ship in August.

We'll also need to work out an approach to port this work down to 6.x. (We probably won't ship a new version of 5.x, @GuardRex, sorry.) We do plan to ship a 6.16.0.

Thoughts?

Also, P.S., thanks to @advancedrei bugging us, we're working on improving/centralizing documentation so that we have a better place to post "official" statements. See #624.

**Comment by am11** [comment]
@markrendle, thanks for the update. I can understand the pressure near the release milestone. :)

Going by your previous comment:

> If someone in the community has the ability to send us a PR, it's certainly possible for us to include that in the upcoming release (7.0.0)

I prepared pull request #591 against v7.0 branch. Let me give you a brief idea about the approach taken there (because I really this that this is the best candidate solution for the situation you have described):

I have added a set of project files in a new directory with a separate solution file. This way it does not affect how projects are building for other frameworks today. I have done in this way so contributors of the repo do not have to encounter a sudden change in their workflow (principal of least surprise).

The only thing required for v7.0 would be to include this additional assembly produced by new solution (`Microsoft.OData.NetStandard.sln`) in nuget package before the release.

Once v7.0 is out of door, and avid .NET Core consumers are unblocked -- for v7.1, a more integrated approach can be incorporated giving time for OData team to go through the API surface area differences across the framework versions and .NET Core architecture in general.

IMO, this is the shortest way to enable consumers, asserting no hassle on the OData team for v7.0. If there are validation concerns, this can probably be marked as "v7.0 (with experimental .NET Core support)".

**Comment by niemyjski** [comment]
Seriously need to add support for this, the tool chain will change but will be automatically upgraded. The runtime is RTM and stable and this is holding back a lot of libraries from going to .NET Core. You would really win by moving to the new project format even though it's changing as you could make your whole build system easier and your nuget packages more explicit and actually list the supported frameworks..

**Comment by advancedrei** [comment]
There is a way to get WindowsAzure.Storage, OData, and other assemblies into your project manually.

Add the following code to your project.json file:

```
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "portable-net45+win8",
        "portable-net45+win8+wp8+wpa",
        "net40"
      ]
    }
  },
```

If you do this, and you have `WindowsAzure.Storage` in your project, it will install itself and all the OData libraries properly. NOTE I have no idea if the code will actually execute. But it WILL compile.

**Comment by niemyjski** [comment]
@advancedrei yes, we all know this will work but that's not the point. .NET Core is RTM and there is no official support without hacky work arounds that may not work in production as the api surface may be different (but compiles)

**Comment by advancedrei** [comment]
No, actually we don't "all" know this. Some people don't know it yet. And you're right, it may not work in  production, depending on what you deploy it to. But compiling to .NET Core doesn't magically guarantee your code will work in production, either. Be realistic. Your arguments about moving to .NET Core making the team's life easier are laughable. Nothing about this is making anyone's life easier right now.

**Comment by KirilRusev** [comment]
@markdstafford Any progress on .NOT Core support after v 1.0 is officially released? We seriously need this one.

**Comment by GuardRex** [comment]
@KirilRusev See: https://github.com/OData/odata.net/issues/568#issuecomment-230068541 ... TL;DR hopefully in August.

**Comment by MaximRouiller** [comment]
@GuardRex You have about 32 hours left (PST). :stuck_out_tongue:

**Comment by GuardRex** [comment]
Well ... I did say ...

> hopefully

**Comment by MaximRouiller** [comment]
@GuardRex 

Yeah, I know. I'm just kidding you a bit. ;-)

Anyway, it would be fun to have an ETA from the Microsoft Team on this.

**Comment by talynone** [comment]
Bump, my team is itching for .NET core support.

**Comment by Eneuman** [comment]
Any ETA for beta package ?

**Comment by djanosik** [comment]
Are `netstandard` packages coming anytime soon?

BTW: There is a workaround. Use version `6.15.0` and import `dnxcore50` target framework.

**Comment by chadwackerman** [comment]
Did @markdstafford seriously punt this down the road six months ago over "tooling concerns" and a desire to "minimize rework"? 

Do you not understand what "platform" means? It means you do double the churn and double the work to minimize the exponential increase of work for us poor suckers down the chain. This is also why Microsoft makes 1.6 billion dollars a week.

I'm sure it's way more fun to make a new version than actually fix or ship the current one (the Entity Framework guys have made a lifestyle out of this) but at some point doesn't it feel a little odd not to help your external customers or even the internal Microsoft groups you're holding up?

https://github.com/Azure/azure-storage-net/issues/372

**Comment by MaximRouiller** [comment]
@chadwackerman To be fair... we're already over "6 months ago" today.

**Comment by raffaeu** [comment]
Guys any update?
We want to move from Web Api 2.2 to Core but we can't.
On Web Api 2.2 we can't use the newly OData 7.0 because there are tons of breaking changes in code.
We can't migrate to Web Api Core because there is no support to OData
We can't stay on it because your current implementation of OData miss $search and $expand -< nested $filter. So, do you want us to move to Node.js or do you think it's time to implement the missing pieces?

**Comment by patrickmichalina** [comment]
Is the OData team understaffed or is MS dropping the project?

**Comment by robertmclaws** [comment]
Team is understaffed, and I believe is in transition back to the US. This is not something I would personally expect any time soon. Speaking for myself here, and not the team, you should plan on staying on Web API 2.2 in 2017. Even if they release Core OData support (which requires EF Core improvements, System.Spatial porting, etc) it's still going to be buggy until they stabilize.

I don't think OData.NetCore is going to bring nested filtering anyways. If the filtering is something you need implemented on the server-side, you might consider using RESTier on top of Web API OData. That lets you have WCF Data Services-style Interceptors.

HTH!

**Comment by markdstafford** [comment]
@robertmclaws - you should just be part of the team; you often know more about it than I do. :)

@chadwackerman, @MaximRouiller, @raffaeu, @patrickmichalina - MS is not likely to "drop" the project any time soon given the # of internal dependencies we have on it. Almost all of our O365/Dynamics APIs are OData, several significant Azure APIs are OData, and with the rise of Graph (which is a fancy API gateway) we will continue to need a common language to talk to backend APIs.

Unfortunately, it's not always easy to staff projects that don't directly contribute to the bottom line. We do our best to address both internal asks and external asks. With something as complex as .NET Core, things get even more complicated.

We hear both internal and external asks for .NET Core support, but it's still a nasty set of breaking changes in Web API OData, where most of our adoption is. "Stock" Web API OData APIs (no modifications to out-of-box formatters, routing, etc) should be relatively easy to update. However, the complexity could go up dramatically if you've fiddled with the Web API layer itself.

We talk about addressing this ask regularly (I've had the conversation several times over the past two weeks). I'm happy to share my thinking, but I want to be particularly clear about the fact that it's MY thinking.

I'm no longer worried about the tooling. It should be stable enough at this point. We're also past a big hurdle that we closed with the core libraries 7.x and Web API OData 6.x releases: trimming out some of the old crufty code from OData v1-v3. So we're in a place where we can move forward. I'm meeting with a team in a few minutes that is both notable and wants .NET Core support. I've heard from several others that they would also like .NET Core support.

Based on all this, I *hope* we will invest in the near future - but 1) I still can't guarantee anything, and 2) most likely when we do, it will be another breaking change release. :( Obviously this isn't ideal, but I don't see a good way to avoid it. We are definitely open to suggestions.

For those of you who are able to share what company you work for and how adding .NET Core support would help you, I'd love it if you would send me mail directly at mastaffo@microsoft.com. Official asks from named companies will definitely help me argue for funding this work.

**Comment by chadwackerman** [comment]
One big name company/product you could reference? Microsoft Azure.

Amazon Web Services provides a far greater suite of services than Azure does. And Amazon shipped full .NET Core functionality, across ALL services, in September 2015. In August 2016, they even reduced the dependency to .NET Standard 1.3.

In other words: I can use my preferred Microsoft toolset and language to talk to AWS but not Azure. I can perform full C# automation against Amazon Elastic Beanstalk (whatever the hell that is) but I require multiple workarounds merely to copy a file to Azure blob storage.

It is easier to talk to Amazon AWS with Amazon's .NET libraries than it is to talk to Microsoft Azure with Microsoft's .NET libraries! This is preposterous.

In 2014 Microsoft broke the ability to write a signed value to Microsoft SQL Server. Meanwhile I can write unsigned values to Redis or SQLite. This one in particular has been at the top of UserVoice sites for years.

This risks sounding like a disjointed rant but if you track the various bugs and Microsoft teams pointing dependency magic wands at each other, one of the frequent bridges you find yourself crossing over and over is right here in OData-land. 

Microsoft's inability to break these obvious dependency issues directly impacts Azure's ability to grow. Microsoft's pushing people to competitors by not providing basic cross-platform tools. Outside of the most trivial rigged tradeshow demos, things simply do not work right now.

**Comment by djanosik** [comment]
Well, I don't really need ASP.NET Core Web APIs OData integration. I just need to reference OData libs from .NET Standard library. It should take no time to make that possible, right? It is already compatible with `dnxcore50`.

**Comment by raffaeu** [comment]
@markdstafford I don't want to blown my own trumpet here, but I just want to give you the insights from one of your customer/consumer (me).

I work for a medium Software House and 2 years ago we started to migrate our product from Client/Server to full SaaS. Of course, we kept .NET because we are a Microsoft Gold Partner so I choose Web Api + OData and on the Client side I choose HTML5 with Angular. 
Win win solution except that now that we are live on Azure and we have thousands of users we started to feel the limit of "Microsoft" OData implementation. nested $filter doesn't work, $search has never been implemented and many more missing or buggy functionalities.

More over, Microsoft forced us to move, from NHibernate to Entity Framework just because you can't provide to us a decent Lambda Expression converter so we are forced to have OData coupled tightly with Entity Framework.

Fine for me, but now we are on OData 5.6 and we want to upgrade because it looks like some bugs have been fixed. We tried and Microsoft changed/moved classes and signatures of methods between minor version upgrade causing my team a big headache.

So, considering we are 100% SaaS we choose to have a look at ASP.NET Core and maybe migrate our code to a v 2.0 which would be 100% cross-platform. But we can't. We can't because ASP.NET Core is at the version 1.1 but it's incomplete compared to the previous .NET ASP.NET. 

This has been like this for years. Entity Framework was a beta until version 4.5 while OData in my opinion never became a real RTM (we still need to implement a decent CORS filter ...). OWIN Identity is just a nightmare to be configured with ASP.NET Identity and it doesn't implement correctly OAuth 2.0.

So, thanks to my little company, Microsoft has 7000 users on Azure this year which are generating some revenue and there are thousands of little companies like mine which are making Microsoft a reality. So, when are we going to start to have the support that we deserve?
Do I have now implement my own OData library on top of Web Api and share it on GitHub? Is this how Microsoft technologies are intended?

**Comment by chadwackerman** [comment]
> We tried and Microsoft changed/moved classes and signatures of methods between minor version upgrade causing my team a big headache.

A bit off topic but I wanted to call this out. Some of these technologies really seem to lack consistent technical leadership across versions. If you're going to add a layer or significant functionality, have at it. But there's an awful lot of needless, tweaky renaming going on. 

Just because you can hit control-R+R in Redmond, it doesn't magically make 200 person-years of MSDN examples and StackOverflow knowledge magically update as well. Let alone the dev cost down the chain. Change the type/signature, refactor the functionality block, OR rename the assembly. Do all three at once and I can't even find your code, let alone figure out how to call it. I'm trying to port to Azure, maybe now isn't the best time to play hide and seek with your latest odd variation of dependency injection or latest goofy authentication refactor.

If Microsoft can keep the same stupid cut and paste behavior in Excel for 30 years, perhaps it doesn't need to change the type and structure of HTTP result codes every six months?

Microsoft surely has all the sample code from StackOverflow plus every sample ever published to MSDN. After you make a breaking change, perhaps get someone from an unrelated team in front of your computer and watch them try to make your "new and improved" API work on the existing code? A few cycles of that and I bet we'll see better API review and smarter porting tools immediately. A two page MSDN porting guide that doesn't even show using/namespace blocks doesn't cut it in 2017.

**Comment by Petermarcu** [comment]
@djanosik , if you import "dnxcore50" you should be able to reference the libraries and there is a PR out to make that import go away. https://github.com/OData/odata.net/pull/734 . I hope that PR can go in soon and packages made available...

**Comment by Petermarcu** [comment]
Here are some samples of how you can use OData today on .NET Core. The key is the imports statements that give NuGet hints about compatibility between different framework names. There is work planned to make this automatic but its not released yet.

__Application:__

```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable",
    "emitEntryPoint": true
  },
  "dependencies": {},
  "frameworks": {
    "netcoreapp1.1": {
      "dependencies": {
        "Microsoft.NETCore.App": {
          "type": "platform",
          "version": "1.1.0"
        },
        "Microsoft.OData.Core": "6.15.0"
      },
      "imports": "dnxcore50"
    }
  }
}
```

__Library:__

```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable"
  },
  "dependencies": {},
  "frameworks": {
    "netstandard1.6": {
      "dependencies": {
        "NETStandard.Library": "1.6.1",
        "Microsoft.OData.Core": "6.15.0"
      },
      "imports": "dnxcore50"
    }
  }
}
````

__Library as a transitive reference through Azure Storage:__

```
{
  "version": "1.0.0-*",
  "buildOptions": {
    "debugType": "portable"
  },
  "dependencies": {},
  "frameworks": {
    "netstandard1.6": {
      "dependencies": {
        "NETStandard.Library": "1.6.1",
        "WindowsAzure.Storage": "8.0.1"
      },
      "imports": ["dnxcore50", "portable-net45+wp8+win8+wpa"]
    }
  }
}
```

**Comment by chadwackerman** [comment]
This generates a command line executable that runs on Ubuntu 16.04 as well as Windows. It uses EF Core and even drags in AspNetCore Identity along the way. Mostly I'm amazed at how little it shares with the other workarounds above. (We're all basically hitting this stuff with sticks, just hoping it starts working.)

It's totally idiotic and already outdated because this project format is not only obsolete, it doesn't  even convert properly in Visual Studio 2017 RC. But I'll litter GitHub and Google results with mine in perpetuity as well.

`{
  "version": "1.0.0-*",
  "buildOptions": {
    "emitEntryPoint": true,
    "define": [ "NET_CORE" ]
  },

  "dependencies": {
    "Microsoft.AspNetCore.Identity": "1.1.0",
    "Microsoft.AspNetCore.Identity.EntityFrameworkCore": "1.1.0",
    "Microsoft.EntityFrameworkCore": "1.1.0",
    "Microsoft.EntityFrameworkCore.SqlServer": "1.1.0",
    "Microsoft.Extensions.Configuration": "1.1.0",
    "Microsoft.Extensions.Configuration.Binder": "1.1.0",
    "Microsoft.Extensions.Configuration.FileExtensions": "1.1.0",
    "Microsoft.Extensions.Configuration.Json": "1.1.0",
    "Microsoft.NETCore.App": "1.1.0",
    "WindowsAzure.Storage": "7.2.1"
  },

  "frameworks": {
    "netcoreapp1.1": {
      "imports": [ "dnxcore50", "portable-net45+win8" ]
    }
  },

  "publishOptions": {
    "include": [
      "appsettings*.json"
    ]
  },

  "runtimes": {
    "win10-x64": {},
    "ubuntu.16.04-x64": {}
  }
}`

**Comment by Petermarcu** [comment]
Yeah, thats basically the workaround I described. Yes its in the project.json format. If you are seeing bugs in "dotnet migrate" on a project like this, please let folks know. @piotrpMSFT, sounds like this is a good sample project that may have migration issues.

**Comment by ericlink** [comment]
@markdstafford One option might be to have bounties for these issues and let the community help out?

**Comment by jgoshi** [comment]
Can someone post the sample project that fails to migrate? What are the migration errors you are seeing?

**Comment by Petermarcu** [comment]
I think its the last one from @chadwackerman based on his comments.

**Comment by jgoshi** [comment]
But I still need cs files right? To verify that the migrated project will restore and build properly?

**Comment by am11** [comment]
@markrendle, the real/pure NET Standard 1.1 compliant ODataLib package is now available here: https://www.nuget.org/packages/Microsoft.OData.Core/. No more `dnxcore50` hacks required by consumer.

Note that it only supports the latest OData protocol v4. See #820 for more info on versioning.

**Comment by MaximRouiller** [comment]
@GuardRex 

I totally forgot to ask you "of which year?" when you said "End of August". :wink: 

Joke aside, any development?

**Comment by am11** [comment]
@MaximRouiller, this issue is fixed: https://github.com/OData/odata.net/issues/568#issuecomment-309229449.

**Comment by MaximRouiller** [comment]
So this should be closed then?

**Comment by robward-ms** [comment]
As of version 7.2, ODatalib includes support for .Net Core.
