### ISSUE TITLE
Centralized guidance and documentation

### ISSUE THREAD

**Issue by markdstafford** [OData/odata.net#624]
The documentation at http://odata.github.io/odata.net is a good start, but it's a clunky experience and developers have to jump over to other documentation sites in order to find what they need. The OData team at Microsoft should have one centralized, easy-to-find and easy-to-use documentation experience.

Right now we believe that the docs.microsoft.com experience would be right for our customers. DocFx would allow us to use our current markdown-driven style, keep our documentation in our GitHub repos, intermingle conceptual documentation and API documentation, and generally not have to worry about the output.

We'd love to hear what you think about this approach. The .NET team just put their documentation up at http://docs.microsoft.com/dotnet, so you can use that as a reference for the experience. As I compare to readthedocs.org, the two main features that are missing are documentation versioning and easy alternative format (e.g., PDF) generation. I'm hopeful those features will land soon.

**Comment by advancedrei** [comment]
So, I just spent a little while looking over DocFX, and while there are certain things that are nice (like the .NET Doc XML parsing), the visual design leaves a lot to be desired. The API docs are not very visually attractive. There is not a lot of [visual separation between item types](http://dotnet.github.io/docfx/api/Microsoft.DocAsCode.FileMapping.html#Microsoft_DocAsCode_FileMapping), and the code styling is awful hard to read. Then there is the fact that it's a really complex system, and requires a lot to configure. AND it is dependent on .NET Core RC1, which will introduce unnecessary complexity until they update to RTM (which could be a while)

If you look at http://docs.microsoft.com/net, the styling there is equally terrible. It's cool that they tried to use up the entire screen, but the two columns are too visually-confusing. There are small fonts where there should be large ones, and it's all over the place. I'm sure some people could get used to it, but I personally don't like either one. 

The "articles" part is kind of ok, and the visual styling is definitely better. Though it seems like they built this on the Azure documentation hub (it has the same section hyperlinks at the top of each article, and comments at the bottom), which I've disliked for a long time. Documentation is not the place to be having support conversations.

Of all the options, I personally think that http://docs.asp.net is by far the best documentation experience Microsoft has right now, both visually, and from an implementation standpoint. There are currently tools that can convert .NET XML metadata files to Markdown, so the API docs would be covered (plus, we can come up with a better style than the ASP.NET docs currently have). MkDocs is a well-known tool, and there are dozens of plugins to improve the experience. And you can do so in a way that is easy to understand, whereas DocFX has a lot of features but looks to be overly-complex to configure.

ReadTheDocs also has the best deployment experience, because all you have to do is check in the code, and they compile and deploy it for you. Everything else requires you to handle compilation and deployment yourself, which seems like an unnecessary hassle.

Finally, the .NET Core team does not seem to be on an "awesome-decision-making" spree right now, I'm not sure that it's wise to follow them down unproven paths. Shipping .NET Core on one documentation system and ASP.NET Core on another is one of those bad decisions. Shipping their docs on a platform experience that is still very much an experiment is another one.

Just my $0.02. HTH! 😸

**Comment by markdstafford** [comment]
Documentation has been moved: https://docs.microsoft.com/en-us/odata/.
