### ISSUE TITLE
Prefer IEnumerable<object> over IEnumerable

### ISSUE THREAD

**Issue by Lingxi-Li** [OData/odata.net#640]
`IEnumerable` is deprecated. `IEnumerable<object>` should be used instead. For example, see the `Items` property of `ODataCollectionValue`. This allows LINQ extension methods to be used, which are defined on `IEnumerable<T>`, not `IEnumerable`. As an example, see the [`Skip`](https://msdn.microsoft.com/en-us/library/bb358985(v=vs.110).aspx) extension method.

**Comment by Lingxi-Li** [comment]
Relates to [this](http://stackoverflow.com/q/38451939/1348273) SO thread.

**Comment by Lingxi-Li** [comment]
Some practical implications of this change:

1. Direct support for LINQ extension methods.
2. You can no longer do `= new[] { 1, 2, 3 }`, but have to `= new object[] { 1, 2, 3 }`.
3. Better performance for value-typed element type, because boxing is performed only once when assigning the enumerable. In existing code, boxing needs to be done every time the enumerable is used.

**Comment by Luaancz** [comment]
Have you done performance testing to confirm your suspicions?

In the old case, the array is a nice contiguous array with no indirection - very fast. Whatever boxing you need to do is done on a gen-0 heap and discarded almost immediately - very fast.

In the "improved" case, every single element of the array is a separate object for the whole lifetime of the array, and changing an element in the array means spreading the objects over memory, rather than keeping the array contiguous. And since you have an array of objects, every single item is an unknown - what if someone puts a `string` where you expect an `int`?

If you really want to keep the old system, use `.Cast<object>`. That gives you the same characteristics as the old approach (boxing on iteration, not in the array), and wherever you know the correct type at compile-time, no boxing is necessary (as with your sample code - just make the local `int[]` or `IEnumerable<int>`).

**Comment by Lingxi-Li** [comment]
> In the old case, the array is a nice contiguous array with no indirection - very fast. Whatever boxing you need to do is done on a gen-0 heap and discarded almost immediately - very fast.

Nice point. I haven't thought of that. Will conduct a benchmark test to see whether this change does improve performance in our particular case (we have a standardized benchmark framework).

**Comment by Lingxi-Li** [comment]
This task list is subject to continuous update.
- [ ] Fix `ODataCollectionValue.Items`

**Comment by Lingxi-Li** [comment]
Current benchmark test suggests no meaningful performance difference before and after this change. So, remove the performance tag. Still push this change for its benefit of supporting LINQ extension methods directly.
