### ISSUE TITLE
Enable updating top-level properties to null

### ISSUE THREAD

**Issue by TomDu** [OData/odata.net#645]
Re-enable updating top-level properties to null after "odata.null" is removed (#630).

**Comment by maubin-kl** [comment]
Is there an ETA on this? This is a breaking change from version prior to 6.0.0.

We currently cannot update to 6.0.0 because we have custom actions that returns a null value. We do expect to receive a null value on the client side and instead it is now an exception.

**Comment by maubin-kl** [comment]
@TomDu @robward-ms

**Comment by lpperras** [comment]
@TomDu Any news on this?

**Comment by robward-ms** [comment]
The scenario is not supported per the language of the [spec](http://docs.oasis-open.org/odata/odata/v4.0/odata-v4.0-part1-protocol.html):

11.2.3 Requesting Individual Properties
To retrieve an individual property, the client issues a GET request to the property URL. The property URL is the entity read URL with "/" and the property name appended.
For complex typed properties, the path can be further extended with the name of an individual property of the complex type.
See [OData‑URL] for details.
**_If the property is single-valued and has the null value, the service responds with 204 No Content._**
If the property is not available, for example due to permissions, the service responds with 404 Not Found.

**_So the right thing to do is return 204._** 

However, I've made a change to the library to enable back-compat behavior via a writer validation that is on by default. When turned off, the exception is no longer throws an "value":null is written. Not that thus behavior is not compliant with the latest protocol. See #1093 for the change.

**Comment by robward-ms** [comment]
Add a change to allow the odata@null to be written under 6.x compatibility mode and read unconditionally, see #1093

**Comment by maubin-kl** [comment]
@robward-ms Thanks for making the fix. I understand that this is not in the spec but in order to not break our existing clients integration we still need to support that on our end.

I've reviewed the PR and the changes that you've made. However it's not really apparent to me how can I change the behaviour in my application. 

Where from my WebApiConfig can I set the ODataLibraryCompatibility to version 6.xxxx?

**Comment by robward-ms** [comment]
@maubin-kl - The writer settings would need to be injected into the service container. [This ](https://github.com/OData/WebApi/blob/88c5f01f2ee2d685d873b2ab075909b7da6651f1/src/System.Web.OData/Extensions/HttpRequestMessageExtensions.cs#L317-L330)shows where in WebApi the writer settings are read.

You can read more about ODL and dependency injection [here](http://odata.github.io/odata.net/v7/#01-05-di-support).

**Comment by robward-ms** [comment]
@maubin-kl - So you are using OData.Core 7.4.3 with OData WebApi 6.0.0 and are looking for details on how to inject the setting via WebApi?

I think @biaol-odata had recently worked in that area. @biaol-odata -can you comment on this?

**Comment by maubin-kl** [comment]
@robward-ms That is correct.

**Comment by maubin-kl** [comment]
@robward-ms @biaol-odata 

Hey guys, I still have no idea how to change the settings as mentioned above. This is the only blocking issue remaining before we can release a new version of our application. 

Help would be really appreciated. Thanks

**Comment by biaol-odata** [comment]
On WebApi 6.x, client can customize the service container using a customized configureAction for MapODataServiceRoute method.
https://github.com/OData/WebApi/blob/maintenance-6.x/src/System.Web.OData/Extensions/HttpConfigurationExtensions.cs#L509
The method could be invoked from your client code during Web layer start up, such as inside updateConfiguration method.

In configureAction, you can specify build => builder.AddServicePrototype(new ODataMessageWriterSettings
            {
                EnableMessageStreamDisposal = false,
                MessageQuotas = new ODataMessageQuotas { MaxReceivedMessageSize = Int64.MaxValue },
                LibraryCompatibility = ODataLibraryCompatibility.Version6
            });
to use the Version6 compatibility. (Please adjust it properly if you already have a customized writer setting).

**Comment by maubin-kl** [comment]
Thanks @biaol-odata. It works.

Thanks everyone for your support.
