### ISSUE TITLE
Serialisation of body fails to  Model from JSON if Model has Loop Reference. 

### ISSUE THREAD

**Issue by egbertn** [OData/odata.net#650]
*Short summary (3-5 sentences) describing the issue.*  

### Assemblies affected
*Which assemblies and versions are known to be affected e.g. OData .Net lib 6.15*  

### Reproduce steps
*The simplest set of steps to reproduce the issue. If possible, reference a commit that demonstrates the issue.*  

Person class has reference loops. 

OData method below.
delta stays null!

        [ODataRoute("People({key})")]
        [HttpPut]
        public IHttpActionResult Put([FromODataUri] int key, Delta<Person> delta)

  public class Person
    {
        [System.ComponentModel.DataAnnotations.Key]
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        [ForeignKey("Address")]        
        public int? AddressId { get; set; }
        public virtual Address Address { get; set; }
        public virtual ICollection<Address> Addresses { get; set; }

  public class Address
    {
        [Key]
        public int Id { get; set; }
        public string StreetAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public int Zip { get; set; }
        public virtual ICollection<Address> ChildAddresses { get; set; }
        public virtual Address Parent { get; set; }

### Expected result
*What would happen if there wasn't a bug.*  

delta would not be null. If you remove the reference loop, it works!

### Actual result
*What is actually happening.*  

delta is null

### Additional details
*Optional, details of the root cause if known. Delete this section if you have no additional details to add.*

**Comment by Lingxi-Li** [comment]
Seems like you've been using WebApi instead of ODL. Forward to WebApi issues.

**Comment by egbertn** [comment]
Hi Lingxi, certainly -not-. This is reproducable. Find and download SelfHostingUnitTest (search OWIN Self-Hosted Test Server for Integration Testing of OData and Web API). Add one unit test which updates using a Put. It works. Now give the Person class this virtual ICollection<Person> SubPersons {get;set;} now, the Person, will *not* be serialized. This is because of the loop reference. Every good serializer can handle this, not odata :( I guess the Odata project, does not allow to even insert a custom serializer, guys, this makes this project currently useless for us :( :( (We have spent already so much hours to get it done)

**Comment by Lingxi-Li** [comment]
Dear @egbertn, I agree with you that this is an OData library related issue. Still, you have to know that we have a whole library stack for OData here. In other words, we have a multi-tier design. The involved libraries are, from lowest to highest, [OData.Net (ODL)](https://github.com/OData/odata.net), [WebApi.OData](https://github.com/OData/WebApi), and [RESTier](https://github.com/OData/RESTier). From the code you provided in **Reproduce steps**, I infer that you are using WebApi.OData which is based on OData.Net. So, this issue should actually be submitted to WebApi.OData, so that relevant developers could start looking into it from there. If they find this issue is actually caused by the underlying OData.Net library, they will open-up an appropriate issue here then.
