### ISSUE TITLE
$count query option does not respect case insensitivity

### ISSUE THREAD

**Issue by silkroadscott** [OData/odata.net#718]
If case insensitivity is enabled for an OData web API, the $count query option still does not accept case insensitive values. E.g. $count=true is accepted, but $count=True is not. I would expect the latter to work correctly if case insensitivity is enabled. (Arguably it would be expected to work even without case insensitivity enabled, as the standard Convert.ToBoolean will return true for any mixed case of "true".)
### Assemblies affected

Microsoft.OData.Core 6.15.0.0  
### Reproduce steps

In the startup of an OData web API, allow case insensitivity by using configuration.EnableCaseInsensitive(true); 
### Expected result

/api/resource?$count=True would be an acceptable query and would include the count in the result.
### Actual result

An HTTP-400 is returned. The error response includes a Microsoft.OData.Core.ODataException stating that 'True' is not a valid count option.
### Additional details

The ParseCount method in ODataQueryOptionParser.cs is where the parse is attempted. It currently performs a switch-case on ExpressionConstants.KeywordTrue and ExpressionConstants.KeywordFalse, which limits it to accepting "true" and "false".

> switch (count.Trim())
>             {
>                 case ExpressionConstants.KeywordTrue:
>                     return true;
>                 case ExpressionConstants.KeywordFalse:
>                     return false;
>                 default:
>                     throw new ODataException(Strings.ODataUriParser_InvalidCount(count));
>             }

**Comment by LaylaLiu** [comment]
ODataLib implemented the case insensitive only for identifiers, not for values.

**Comment by gathogojr** [comment]
@silkroadscott @odero @mumbi-o 
Implementing support for case-insensitive variants for query option values  (=> true/false/True/False/TRUE/FALSE/etc) would not be in line with the current OData spec http://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#_Toc26175328
For this reason, the team's position is that this is the expected behaviour, until such a time when the specification is revised in support for case-insensitive values for`$count` query option

Not to be confused with the existing support for case-insensitive query option names - this is what `EnableCaseInsensitive` you cited above applies to. OData WebApi currently accepts `$count`, `$Count`, `$COUNT`, `$coUnt`, etc, unless you explicitly configure the service to be case-sensitive, in which case only `$count` will be considered valid

Your way out for now is to supply the option values as either true or false. I'll proceed to close the issue
