### ISSUE TITLE
Prefer: odata.include-annotations="odata.type" header is not returning Entity response with "odata.type" annotation term

### ISSUE THREAD

**Issue by shiva1982** [OData/odata.net#75]
As per the OData spec (4.5.3), with Prefer: odata.include-annotations="odata.type" header request, the response payload should have annotation term "odata.type".   But it is not returning this in the payload.

TripPin service is also not returning the "odata.type" annotation terms in the response payload.

Example: http://services.odata.org/V4/(S(kdyjy3oe4lybwkpv0aex4gpz))/TripPinServiceRW/People('russellwhyte')

Odata.id and odata.type should be populated by the WebAPI JSON serializer.   Currently this is not available.

**Comment by mikepizzo** [comment]
This is actually by design.

odata.* properties follow annotation syntax in the JSON payload, but they should be thought of as control information, not as annotations, because annotations should be format-neutral and the odata.* properties are specific to the json format (since there is no other way to annotate a json payload, they appear as annotations).  You have some control over the presence of odata.* properties using minimal/intermediate/full metadata levels. If we need finer granularity of control we should figure out a way to manipulate it separate from include-annotations.

**Comment by flieks** [comment]
@mikepizzo sorry it's quite confusing. How can we include all default data annotations & also Display vocabulary for example? We have [Key] (core) & [StringLength] (validation) on properties but it's not returning with the Prefer header. 
What we need desperately is the [Display(Customer.Name)] for example to add 1 string from an expand for example.
