### ISSUE TITLE
Put with IsMediaType works but Post doesn't send stream

### ISSUE THREAD

**Issue by Benjamin-Berry** [OData/odata.net#975]
SetSaveStream works when using existing entity (put) but fails when new entity (post).

### Assemblies affected

 OData .Net lib 6.17.0

### Reproduce steps
Call SetSaveStream with a new entity and save.

var template = new Template();
Container.AddToTemplates(template);
var stream = dlg.OpenFile();
 template.FileName = Path.GetFileNameWithoutExtension(dlg.SafeFileName);
 template.FileType = Path.GetExtension(dlg.SafeFileName);
 Container.SetSaveStream(template, stream, true, "application/octet-stream", template.FileName + template.FileType);
Context.SaveChangesAsync();

[global::Microsoft.OData.Client.Key("TemplateId")]
    [global::Microsoft.OData.Client.HasStream()]
    [global::Microsoft.OData.Client.OriginalNameAttribute("Template")]
    public partial class Template : global::Microsoft.OData.Client.BaseEntityType, global::System.ComponentModel.INotifyPropertyChanged
    {
...

### Expected result
I should see some equivalent to this, which I get when I'm saving an existing entity.

iisexpress.exe Information: 0 : Request, Method=PUT, Url=http://localhost:60220/core/Templates(20)/$value, Message='http://localhost:60220/core/Templates(20)/$value'

### Actual result

Server recieves several calls to compete the json portion of the save but no stream.

iisexpress.exe Information: 0 : Request, Method=POST, Url=http://localhost:60220/core/Templates,
iisexpress.exe Information: 0 : Request, Method=PATCH, Url=http://localhost:60220/core/Templates(20),
isexpress.exe Information: 0 : Request, Method=PUT, Url=http://localhost:60220/core/ActivityTypes(22)/Template/$ref,

**Comment by gathogojr** [comment]
@Benjamin-Berry Since `Template` is a Media Link Entry (MLE) and you're creating a new one, the `POST` request body contains stream while the `PATCH` request body contains a `JSON` payload representing the `Template` object.

If on the other hand you were updating the MLE object, the stream would be sent as a `PUT` request to the [http://localhost:60220/core/Templates(20)/$value](http://localhost:60220/core/Templates(20)/$value) endpoint, while the object properties would be sent as a `PATCH` request to the [http://localhost:60220/core/Templates(20)](http://localhost:60220/core/Templates(20)) endpoint. I hope that clarifies
