### ISSUE TITLE
OData Client 7.4.0-Beta performance and bug

### ISSUE THREAD

**Issue by tchuan** [OData/odata.net#990]
Updated my application from 6.18.0 to 7.4.0 beta, a performance test case showed about 20% decrease. 
Average time run from 10S down to 12S. Sometimes even failed. 

### Assemblies affected

OData Client 7.4.0-Beta

### Reproduce steps

```
    var tasks = new Task[1000];
    for (var i = 0; i < tasks.Length; i++)
    {
        tasks[i] = Task.Run(async () =>
        {
            var entity = await oDataRepository.FirstOrDefaultAsync<SampleEntity>();
            Assert.AreNotEqual(null, entity);
        });
    }

    Task.WaitAll(tasks);
```

### StackTrace:
Test Name:	PerformanceTest
Test Outcome:	Failed
Test Duration:	0:00:28.2052726

Result StackTrace:	
at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.OData.Client.DictionaryExtensions.TryAdd[TKey,TValue](IDictionary`2 dict, TKey key, TValue value)
   at Microsoft.OData.Client.TypeResolver..ctor(ClientEdmModel model, Func`2 resolveTypeFromName, Func`2 resolveNameFromType, IEdmModel serviceModel)
   at Microsoft.OData.Client.RequestInfo..ctor(DataServiceContext context)
   at Microsoft.OData.Client.DataServiceRequest.CreateExecuteResult(Object source, DataServiceContext context, AsyncCallback callback, Object state, String method)
   at Microsoft.OData.Client.DataServiceQuery`1.BeginExecute(AsyncCallback callback, Object state)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory`1.FromAsync(Func`3 beginMethod, Func`2 endMethod, Object state)
   at Microsoft.OData.Client.DataServiceQuery`1.ExecuteAsync()
   at ERM.CRM.OData.Repository.Extentions.ODataExtention.<ExecuteQueryAsync>d__1`1.MoveNext() in xxx.cs:line 41
Result Message:	
Test method PerformanceTest threw exception: 
System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.

**Comment by AlanWong-MS** [comment]
@tchuan, thank you for providing feedback on the 7.4.0-beta library. Regarding your baseline measurement from ODL 6.18.0, which framework were you using? Net40 or Portable?

![image](https://user-images.githubusercontent.com/22382722/32472499-d1cb1732-c317-11e7-8d7e-125e957d160a.png)

**Comment by tchuan** [comment]
I'm using Net40.

**Comment by AlanWong-MS** [comment]
@tchuan, can you try to run the performance test on the 6.18.0 Portable binaries as well and compare it with 7.4.0-beta? This is due to the fact that we're considering removing the Net45 libraries.

**Comment by tchuan** [comment]
Tested on 6.18.0 portable binaries for 4 times and all failed. Same error as 7.4.0-beta.

**Comment by AlanWong-MS** [comment]
@tchuan, great thanks for the info! To re-cap, the 7.4.0-beta package contains only the NetStandard 1.1 libraries and were ported from the 6.18.0 portable binaries. At the moment, here are my thoughts:
- It seems that the failure has existed since 6.x. It is sometimes reproducible with the Net40 binaries and 100% reproducible with the Portable binaries.
- Because the 7.4.0-beta OData Client binary is mostly a framework change, I would say that the 7.4.0-beta and 6.18.0 OData Client binaries are nearly equivalent in code.
- Due to this, I think that the bug is actually from 6.x and not introduced in 7.4.0-beta. This is just to help us narrow down where to find the problem. :)
- Regarding the performance degradation of 20% demonstrated by your tests, I think we'll have to be able to pass the test on 6.18.0 portable binaries to see if the performance impact was introduced in the portable version. If you are not able to get any runs to pass, we'll have to address the test failure issue first.

With that said, I'll work with someone to get a similar test setup to yours and see if we can repro the issue. In the meantime, you're more than welcome to help debug where the issue might be coming from. Thanks again!

**Comment by tchuan** [comment]
@AlanWong-MS  I will try to do some investigations, though last time got a 'Strong Name Validation Failed' when I added odata project as reference,  But will let you know if find anything useful.

**Comment by AlanWong-MS** [comment]
@tchuan, thanks again for your feedback. Regarding the "Strong Name Validation Failed" error, have you seen this [link](https://blogs.msdn.microsoft.com/keithmg/2012/03/20/strong-name-validation-failed-exception-from-hresult-0x8013141a/)?

We have a [MyGet package](https://www.myget.org/feed/odlnightly/package/nuget/Microsoft.OData.Client/7.3.1-Nightly201708142037) that contains the Net45 binaries for OData Client 7.x. If you can get reproducibility and performance numbers on that library as well, then we should have a better understanding on where the degradation may be.

**Comment by tchuan** [comment]
@AlanWong-MS , found the reason.
For PORTABLELIB, ClientEdmModel class uses generic Dictionary, which is not thread safe. So in the performance test, when writing and reading at same time, the ConcurrentEdmSchemaDictionary will throw "Index was outside the bounds of the array."

See the code below, I think .net standard 1.1 does support ConcurrentDictionary. Could we replace it with a single line?
`#if PORTABLELIB
    // Windows Phone 8.0 doesn't support ConcurrentDictionary
    using ConcurrentEdmSchemaDictionary = System.Collections.Generic.Dictionary<string, Edm.IEdmSchemaElement>;
#else
    using ConcurrentEdmSchemaDictionary = System.Collections.Concurrent.ConcurrentDictionary<string, Edm.IEdmSchemaElement>;
#endi`

**Comment by robertmclaws** [comment]
.NET Standard 1.1 will indeed support it if you include the System.Threading.Tasks NuGet package into the project.

I would think that you wouldn't do that JUST for PORTABLELIB, that should be a change for any version.

**Comment by AlanWong-MS** [comment]
@tchuan, nice find! To address that code comment `// Windows Phone 8.0 doesn't support ConcurrentDictionary`, we made a conscious decision to loosen our requirement on Windows Phone 8.0 (since it's a platform that has been superseded now), despite the fact that it's part of the NetStandard 1.1 matrix. So yes, I would say that removing the #if/#else preprocessor is a legitimate approach to the issue; concurrency applies to both the non-portable and portable libs per @robertmclaws's point.

@tchuan, can you confirm that this change enables you to run your performance test without failure? If so, can you please open a PR with your proposed fix? I think this is [the code section](https://github.com/OData/odata.net/blob/master/src/Microsoft.OData.Client/ClientEdmModel.cs#L25) to which you're referring.

**Comment by AlanWong-MS** [comment]
Thanks for the PR to address the race condition issue @tchuan. I believe the remaining part of this open issue is regarding the performance drop between the non-portable and portable versions.
